/* 
 * Copyright (C) 2014, Enrico M. Crisostomo
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.netbeans.gnu.autotools.autoconf.completion;

/**
 *
 * @author Enrico M. Crisostomo
 */
public enum AutoconfMacros {

    AC_ARG_VAR("AC_ARG_VAR", "Setting-Output-Variables.html"),
    AC_ARG_ENABLE("AC_ARG_ENABLE", "Package-Options.html"),
    AC_ARG_PROGRAM("AC_ARG_PROGRAM", "Transforming-Names.html"),
    AC_ARG_WITH("AC_ARG_WITH", "External-Software.html"),
    AC_AUTOCONF_VERSION("AC_AUTOCONF_VERSION", "Versioning.html"),
    AC_BEFORE("AC_BEFORE", "Suggested-Ordering.html"),
    AC_C_BACKSLASH_A("AC_C_BACKSLASH_A", "C-Compiler.html"),
    AC_C_BIGENDIAN("AC_C_BIGENDIAN", "C-Compiler.html"),
    AC_C_CHAR_UNSIGNED("AC_C_CHAR_UNSIGNED", "C-Compiler.html"),
    AC_C_CONST("AC_C_CONST", "C-Compiler.html"),
    AC_C_FLEXIBLE_ARRAY_MEMBER("AC_C_FLEXIBLE_ARRAY_MEMBER", "C-Compiler.html"),
    AC_C_INLINE("AC_C_INLINE", "C-Compiler.html"),
    AC_C_PROTOTYPES("AC_C_PROTOTYPES", "C-Compiler.html"),
    AC_C_RESTRICT("AC_C_RESTRICT", "C-Compiler.html"),
    AC_C_STRINGIZE("AC_C_STRINGIZE", "C-Compiler.html"),
    AC_C_TYPEOF("AC_C_TYPEOF", "C-Compiler.html"),
    AC_C_VARARRAYS("AC_C_VARARRAYS", "C-Compiler.html"),
    AC_C_VOLATILE("AC_C_VOLATILE", "C-Compiler.html"),
    AC_CACHE_CHECK("AC_CACHE_CHECK", "Caching-Results.html"),
    AC_CACHE_LOAD("AC_CACHE_LOAD", "Cache-Checkpointing.html"),
    AC_CACHE_SAVE("AC_CACHE_SAVE", "Cache-Checkpointing.html"),
    AC_CACHE_VAL("AC_CACHE_VAL", "Caching-Results.html"),
    AC_CANONICAL_BUILD("AC_CANONICAL_BUILD", "Canonicalizing.html"),
    AC_CANONICAL_HOST("AC_CANONICAL_HOST", "Canonicalizing.html"),
    AC_CANONICAL_TARGET("AC_CANONICAL_TARGET", "Canonicalizing.html"),
    AC_CHECK_ALIGNOF("AC_CHECK_ALIGNOF", "Generic-Compiler-Characteristics.html"),
    AC_CHECK_DECL("AC_CHECK_DECL", "Generic-Declarations.html"),
    AC_CHECK_DECLS("AC_CHECK_DECLS", "Generic-Declarations.html"),
    AC_CHECK_DECLS_ONCE("AC_CHECK_DECLS_ONCE", "Generic-Declarations.html"),
    AC_CHECK_FILE("AC_CHECK_FILE", "Files.html"),
    AC_CHECK_FILES("AC_CHECK_FILES", "Files.html"),
    AC_CHECK_FUNC("AC_CHECK_FUNC", "Generic-Functions.html"),
    AC_CHECK_FUNCS("AC_CHECK_FUNCS", "Generic-Functions.html"),
    AC_CHECK_FUNCS_ONCE("AC_CHECK_FUNCS_ONCE", "Generic-Functions.html"),
    AC_CHECK_LIB("AC_CHECK_LIB", "Libraries.html"),
    AC_CHECK_HEADER("AC_CHECK_HEADER", "Generic-Headers.html"),
    AC_CHECK_HEADER_STDBOOL("AC_CHECK_HEADER_STDBOOL", "Particular-Headers.html"),
    AC_CHECK_HEADERS("AC_CHECK_HEADERS", "Generic-Headers.html"),
    AC_CHECK_HEADERS_ONCE("AC_CHECK_HEADERS_ONCE", "Generic-Headers.html"),
    AC_CHECK_MEMBER("AC_CHECK_MEMBER", "Generic-Structures.html"),
    AC_CHECK_MEMBERS("AC_CHECK_MEMBERS", "Generic-Structures.html"),
    AC_CHECK_PROG("AC_CHECK_PROG", "Generic-Programs.html"),
    AC_CHECK_PROGS("AC_CHECK_PROGS", "Generic-Programs.html"),
    AC_CHECK_SIZEOF("AC_CHECK_SIZEOF", "Generic-Compiler-Characteristics.html"),
    AC_CHECK_TARGET_TOOL("AC_CHECK_TARGET_TOOL", "Generic-Programs.html"),
    AC_CHECK_TARGET_TOOLS("AC_CHECK_TARGET_TOOLS", "Generic-Programs.html"),
    AC_CHECK_TYPE("AC_CHECK_TYPE", "Generic-Types.html"),
    AC_CHECK_TYPES("AC_CHECK_TYPES", "Generic-Types.html"),
    AC_CHECK_TOOL("AC_CHECK_TOOL", "Generic-Programs.html"),
    AC_CHECK_TOOLS("AC_CHECK_TOOLS", "Generic-Programs.html"),
    AC_COMPILE_IFELSE("AC_COMPILE_IFELSE", "Running-the-Compiler.html"),
    AC_COMPUTE_INT("AC_COMPUTE_INT", "Generic-Compiler-Characteristics.html"),
    AC_CONFIG_AUX_DIR("AC_CONFIG_AUX_DIR", "Input.html"),
    AC_CONFIG_COMMANDS("AC_CONFIG_COMMANDS", "Configuration-Commands.html"),
    AC_CONFIG_COMMANDS_PRE("AC_CONFIG_COMMANDS_PRE", "Configuration-Commands.html"),
    AC_CONFIG_COMMANDS_POST("AC_CONFIG_COMMANDS_POST", "Configuration-Commands.html"),
    AC_CONFIG_FILES("AC_CONFIG_FILES", "Configuration-Files.html"),
    AC_CONFIG_LIBOBJ_DIR("AC_CONFIG_LIBOBJ_DIR", "Generic-Functions.html"),
    AC_CONFIG_LINKS("AC_CONFIG_LINKS", "Configuration-Links.html"),
    AC_CONFIG_MACRO_DIR("AC_CONFIG_MACRO_DIR", "Input.html"),
    AC_CONFIG_MACRO_DIRS("AC_CONFIG_MACRO_DIRS", "Input.html"),
    AC_CONFIG_SRCDIR("AC_CONFIG_SRCDIR", "Input.html"),
    AC_CONFIG_SUBDIRS("AC_CONFIG_SUBDIRS", "Subdirectories.html"),
    AC_COPYRIGHT("AC_COPYRIGHT", "Notices.html"),
    AC_DEFINE("AC_DEFINE", "Defining-Symbols.html"),
    AC_DEFINE_UNQUOTED("AC_DEFINE_UNQUOTED", "Defining-Symbols.html"),
    AC_DEFUN("AC_DEFUN", "Macro-Definitions.html"),
    AC_DEFUN_ONCE("AC_DEFUN_ONCE", "One_002dShot-Macros.html"),
    AC_DIAGNOSE("AC_DIAGNOSE", "Reporting-Messages.html"),
    AC_DISABLE_OPTION_CHECKING("AC_DISABLE_OPTION_CHECKING", "Option-Checking.html"),
    AC_EGREP_CPP("AC_EGREP_CPP", "Running-the-Preprocessor.html"),
    AC_EGREP_HEADER("AC_EGREP_HEADER", "Running-the-Preprocessor.html"),
    AC_ERLANG_CHECK_LIB("AC_ERLANG_CHECK_LIB", "Erlang-Libraries.html"),
    AC_ERLANG_NEED_ERL("AC_ERLANG_NEED_ERL", "Erlang-Compiler-and-Interpreter.html"),
    AC_ERLANG_NEED_ERLC("AC_ERLANG_NEED_ERLC", "Erlang-Compiler-and-Interpreter.html"),
    AC_ERLANG_PATH_ERL("AC_ERLANG_PATH_ERL", "Erlang-Compiler-and-Interpreter.html"),
    AC_ERLANG_PATH_ERLC("AC_ERLANG_PATH_ERLC", "Erlang-Compiler-and-Interpreter.html"),
    AC_ERLANG_SUBST_ERTS_VER("AC_ERLANG_SUBST_ERTS_VER", "Erlang-Libraries.html"),
    AC_ERLANG_SUBST_INSTALL_LIB_DIR("AC_ERLANG_SUBST_INSTALL_LIB_DIR", "Erlang-Libraries.html"),
    AC_ERLANG_SUBST_INSTALL_LIB_SUBDIR("AC_ERLANG_SUBST_INSTALL_LIB_SUBDIR", "Erlang-Libraries.html"),
    AC_ERLANG_SUBST_LIB_DIR("AC_ERLANG_SUBST_LIB_DIR", "Erlang-Libraries.html"),
    AC_ERLANG_SUBST_ROOT_DIR("AC_ERLANG_SUBST_ROOT_DIR", "Erlang-Libraries.html"),
    AC_F77_DUMMY_MAIN("AC_F77_DUMMY_MAIN", "Fortran-Compiler.html"),
    AC_F77_FUNC("AC_F77_FUNC", "Fortran-Compiler.html"),
    AC_F77_IMPLICIT_NONE("AC_F77_IMPLICIT_NONE", "Fortran-Compiler.html"),
    AC_F77_LIBRARY_LDFLAGS("AC_F77_LIBRARY_LDFLAGS", "Fortran-Compiler.html"),
    AC_F77_MAIN("AC_F77_MAIN", "Fortran-Compiler.html"),
    AC_F77_WRAPPERS("AC_F77_WRAPPERS", "Fortran-Compiler.html"),
    AC_FATAL("AC_FATAL", "Reporting-Messages.html"),
    AC_FC_CHECK_BOUNDS("AC_FC_CHECK_BOUNDS", "Fortran-Compiler.html"),
    AC_FC_DUMMY_MAIN("AC_FC_DUMMY_MAIN", "Fortran-Compiler.html"),
    AC_FC_FIXEDFORM("AC_FC_FIXEDFORM", "Fortran-Compiler.html"),
    AC_FC_FREEFORM("AC_FC_FREEFORM", "Fortran-Compiler.html"),
    AC_FC_FUNC("AC_FC_FUNC", "Fortran-Compiler.html"),
    AC_FC_IMPLICIT_NONE("AC_FC_IMPLICIT_NONE", "Fortran-Compiler.html"),
    AC_FC_LIBRARY_LDFLAGS("AC_FC_LIBRARY_LDFLAGS", "Fortran-Compiler.html"),
    AC_FC_LINE_LENGTH("AC_FC_LINE_LENGTH", "Fortran-Compiler.html"),
    AC_FC_MAIN("AC_FC_MAIN", "Fortran-Compiler.html"),
    AC_FC_MODULE_EXTENSION("AC_FC_MODULE_EXTENSION", "Fortran-Compiler.html"),
    AC_FC_MODULE_FLAG("AC_FC_MODULE_FLAG", "Fortran-Compiler.html"),
    AC_FC_MODULE_OUTPUT_FLAG("AC_FC_MODULE_OUTPUT_FLAG", "Fortran-Compiler.html"),
    AC_FC_PP_DEFINE("AC_FC_PP_DEFINE", "Fortran-Compiler.html"),
    AC_FC_PP_SRCEXT("AC_FC_PP_SRCEXT", "Fortran-Compiler.html"),
    AC_FC_SRCEXT("AC_FC_SRCEXT", "Fortran-Compiler.html"),
    AC_FC_WRAPPERS("AC_FC_WRAPPERS", "Fortran-Compiler.html"),
    AC_FUNC_ALLOCA("AC_FUNC_ALLOCA", "Particular-Functions.html"),
    AC_FUNC_CHOWN("AC_FUNC_CHOWN", "Particular-Functions.html"),
    AC_FUNC_CLOSEDIR_VOID("AC_FUNC_CLOSEDIR_VOID", "Particular-Functions.html"),
    AC_FUNC_ERROR_AT_LINE("AC_FUNC_ERROR_AT_LINE", "Particular-Functions.html"),
    AC_FUNC_FNMATCH("AC_FUNC_FNMATCH", "Particular-Functions.html"),
    AC_FUNC_FNMATCH_GNU("AC_FUNC_FNMATCH_GNU", "Particular-Functions.html"),
    AC_FUNC_FORK("AC_FUNC_FORK", "Particular-Functions.html"),
    AC_FUNC_FSEEKO("AC_FUNC_FSEEKO", "Particular-Functions.html"),
    AC_FUNC_GETGROUPS("AC_FUNC_GETGROUPS", "Particular-Functions.html"),
    AC_FUNC_GETLOADAVG("AC_FUNC_GETLOADAVG", "Particular-Functions.html"),
    AC_FUNC_GETMNTENT("AC_FUNC_GETMNTENT", "Particular-Functions.html"),
    AC_FUNC_GETPGRP("AC_FUNC_GETPGRP", "Particular-Functions.html"),
    AC_FUNC_LSTAT_FOLLOWS_SLASHED_SYMLINK("AC_FUNC_LSTAT_FOLLOWS_SLASHED_SYMLINK", "Particular-Functions.html"),
    AC_FUNC_MALLOC("AC_FUNC_MALLOC", "Particular-Functions.html"),
    AC_FUNC_MBRTOWC("AC_FUNC_MBRTOWC", "Particular-Functions.html"),
    AC_FUNC_MEMCMP("AC_FUNC_MEMCMP", "Particular-Functions.html"),
    AC_FUNC_MKTIME("AC_FUNC_MKTIME", "Particular-Functions.html"),
    AC_FUNC_MMAP("AC_FUNC_MMAP", "Particular-Functions.html"),
    AC_FUNC_OBSTACK("AC_FUNC_OBSTACK", "Particular-Functions.html"),
    AC_FUNC_REALLOC("AC_FUNC_REALLOC", "Particular-Functions.html"),
    AC_FUNC_SELECT_ARGTYPES("AC_FUNC_SELECT_ARGTYPES", "Particular-Functions.html"),
    AC_FUNC_SETPGRP("AC_FUNC_SETPGRP", "Particular-Functions.html"),
    AC_FUNC_STAT("AC_FUNC_STAT", "Particular-Functions.html"),
    AC_FUNC_LSTAT("AC_FUNC_LSTAT", "Particular-Functions.html"),
    AC_FUNC_STRCOLL("AC_FUNC_STRCOLL", "Particular-Functions.html"),
    AC_FUNC_STRERROR_R("AC_FUNC_STRERROR_R", "Particular-Functions.html"),
    AC_FUNC_STRFTIME("AC_FUNC_STRFTIME", "Particular-Functions.html"),
    AC_FUNC_STRTOD("AC_FUNC_STRTOD", "Particular-Functions.html"),
    AC_FUNC_STRTOLD("AC_FUNC_STRTOLD", "Particular-Functions.html"),
    AC_FUNC_STRNLEN("AC_FUNC_STRNLEN", "Particular-Functions.html"),
    AC_FUNC_UTIME_NULL("AC_FUNC_UTIME_NULL", "Particular-Functions.html"),
    AC_FUNC_VPRINTF("AC_FUNC_VPRINTF", "Particular-Functions.html"),
    AC_HEADER_ASSERT("AC_HEADER_ASSERT", "Particular-Headers.html"),
    AC_HEADER_DIRENT("AC_HEADER_DIRENT", "Particular-Headers.html"),
    AC_HEADER_MAJOR("AC_HEADER_MAJOR", "Particular-Headers.html"),
    AC_HEADER_RESOLV("AC_HEADER_RESOLV", "Particular-Headers.html"),
    AC_HEADER_STAT("AC_HEADER_STAT", "Particular-Headers.html"),
    AC_HEADER_STDBOOL("AC_HEADER_STDBOOL", "Particular-Headers.html"),
    AC_HEADER_STDC("AC_HEADER_STDC", "Particular-Headers.html"),
    AC_HEADER_SYS_WAIT("AC_HEADER_SYS_WAIT", "Particular-Headers.html"),
    AC_HEADER_TIME("AC_HEADER_TIME", "Particular-Headers.html"),
    AC_HEADER_TIOCGWINSZ("AC_HEADER_TIOCGWINSZ", "Particular-Headers.html"),
    AC_INCLUDES_DEFAULT("AC_INCLUDES_DEFAULT", "Default-Includes.html"),
    AC_INIT("AC_INIT", "Initializing-configure.html"),
    AC_LANG("AC_LANG", "Language-Choice.html"),
    AC_LANG_ASSERT("AC_LANG_ASSERT", "Language-Choice.html"),
    AC_LANG_CALL("AC_LANG_CALL", "Generating-Sources.html"),
    AC_LANG_CONFTEST("AC_LANG_CONFTEST", "Generating-Sources.html"),
    AC_LANG_DEFINES_PROVIDED("AC_LANG_DEFINES_PROVIDED", "Generating-Sources.html"),
    AC_LANG_FUNC_LINK_TRY("AC_LANG_FUNC_LINK_TRY", "Generating-Sources.html"),
    AC_LANG_POP("AC_LANG_POP", "Language-Choice.html"),
    AC_LANG_PROGRAM("AC_LANG_PROGRAM", "Generating-Sources.html"),
    AC_LANG_PUSH("AC_LANG_PUSH", "Language-Choice.html"),
    AC_LANG_SOURCE("AC_LANG_SOURCE", "Generating-Sources.html"),
    AC_LANG_WERROR("AC_LANG_WERROR", "Generic-Compiler-Characteristics.html"),
    AC_LIBOBJ("AC_LIBOBJ", "Generic-Functions.html"),
    AC_LIBSOURCE("AC_LIBSOURCE", "Generic-Functions.html"),
    AC_LIBSOURCES("AC_LIBSOURCES", "Generic-Functions.html"),
    AC_LINK_IFELSE("AC_LINK_IFELSE", "Running-the-Linker.html"),
    AC_MSG_CHECKING("AC_MSG_CHECKING", "Printing-Messages.html"),
    AC_MSG_ERROR("AC_MSG_ERROR", "Printing-Messages.html"),
    AC_MSG_FAILURE("AC_MSG_FAILURE", "Printing-Messages.html"),
    AC_MSG_NOTICE("AC_MSG_NOTICE", "Printing-Messages.html"),
    AC_MSG_RESULT("AC_MSG_RESULT", "Printing-Messages.html"),
    AC_MSG_WARN("AC_MSG_WARN", "Printing-Messages.html"),
    AC_OPENMP("AC_OPENMP", "Generic-Compiler-Characteristics.html"),
    AC_OUTPUT("AC_OUTPUT", "Output.html"),
    AC_PACKAGE_BUGREPORT("AC_PACKAGE_BUGREPORT", "Initializing-configure.html"),
    AC_PACKAGE_NAME("AC_PACKAGE_NAME", "Initializing-configure.html"),
    AC_PACKAGE_STRING("AC_PACKAGE_STRING", "Initializing-configure.html"),
    AC_PACKAGE_TARNAME("AC_PACKAGE_TARNAME", "Initializing-configure.html"),
    AC_PACKAGE_URL("AC_PACKAGE_URL", "Initializing-configure.html"),
    AC_PACKAGE_VERSION("AC_PACKAGE_VERSION", "Initializing-configure.html"),
    AC_PATH_PROG("AC_PATH_PROG", "Generic-Programs.html"),
    AC_PATH_PROGS("AC_PATH_PROGS", "Generic-Programs.html"),
    AC_PATH_PROGS_FEATURE_CHECK("AC_PATH_PROGS_FEATURE_CHECK", "Generic-Programs.html"),
    AC_PATH_TARGET_TOOL("AC_PATH_TARGET_TOOL", "Generic-Programs.html"),
    AC_PATH_TOOL("AC_PATH_TOOL", "Generic-Programs.html"),
    AC_PATH_X("AC_PATH_X", "System-Services.html"),
    AC_PATH_XTRA("AC_PATH_XTRA", "System-Services.html"),
    AC_PREFIX_DEFAULT("AC_PREFIX_DEFAULT", "Default-Prefix.html"),
    AC_PREFIX_PROGRAM("AC_PREFIX_PROGRAM", "Default-Prefix.html"),
    AC_PREPROC_IFELSE("AC_PREPROC_IFELSE", "Running-the-Preprocessor.html"),
    AC_PREREQ("AC_PREREQ", "Versioning.html"),
    AC_PRESERVE_HELP_ORDER("AC_PRESERVE_HELP_ORDER", "Help-Formatting.html"),
    AC_PROG_AWK("AC_PROG_AWK", "Particular-Programs.html"),
    AC_PROG_CC("AC_PROG_CC", "C-Compiler.html"),
    AC_PROG_CC_C_O("AC_PROG_CC_C_O", "C-Compiler.html"),
    AC_PROG_CC_C89("AC_PROG_CC_C89", "C-Compiler.html"),
    AC_PROG_CC_C99("AC_PROG_CC_C99", "C-Compiler.html"),
    AC_PROG_CC_STDC("AC_PROG_CC_STDC", "C-Compiler.html"),
    AC_PROG_CPP("AC_PROG_CPP", "C-Compiler.html"),
    AC_PROG_CPP_WERROR("AC_PROG_CPP_WERROR", "C-Compiler.html"),
    AC_PROG_CXX("AC_PROG_CXX", "C_002b_002b-Compiler.html"),
    AC_PROG_CXX_C_O("AC_PROG_CXX_C_O", "C_002b_002b-Compiler.html"),
    AC_PROG_CXXCPP("AC_PROG_CXXCPP", "C_002b_002b-Compiler.html"),
    AC_PROG_EGREP("AC_PROG_EGREP", "Particular-Programs.html"),
    AC_PROG_F77("AC_PROG_F77", "Fortran-Compiler.html"),
    AC_PROG_F77_C_O("AC_PROG_F77_C_O", "Fortran-Compiler.html"),
    AC_PROG_FC("AC_PROG_FC", "Fortran-Compiler.html"),
    AC_PROG_FC_C_O("AC_PROG_FC_C_O", "Fortran-Compiler.html"),
    AC_PROG_FGREP("AC_PROG_FGREP", "Particular-Programs.html"),
    AC_PROG_GCC_TRADITIONAL("AC_PROG_GCC_TRADITIONAL", "C-Compiler.html"),
    AC_PROG_GO("AC_PROG_GO", "Go-Compiler.html"),
    AC_PROG_GREP("AC_PROG_GREP", "Particular-Programs.html"),
    AC_PROG_INSTALL("AC_PROG_INSTALL", "Particular-Programs.html"),
    AC_PROG_LEX("AC_PROG_LEX", "Particular-Programs.html"),
    AC_PROG_LN_S("AC_PROG_LN_S", "Particular-Programs.html"),
    AC_PROG_MAKE_SET("AC_PROG_MAKE_SET", "Output.html"),
    AC_PROG_MKDIR_P("AC_PROG_MKDIR_P", "Particular-Programs.html"),
    AC_PROG_OBJC("AC_PROG_OBJC", "Objective-C-Compiler.html"),
    AC_PROG_OBJCPP("AC_PROG_OBJCPP", "Objective-C-Compiler.html"),
    AC_PROG_OBJCXX("AC_PROG_OBJCXX", "Objective-C_002b_002b-Compiler.html"),
    AC_PROG_OBJCXXCPP("AC_PROG_OBJCXXCPP", "Objective-C_002b_002b-Compiler.html"),
    AC_PROG_RANLIB("AC_PROG_RANLIB", "Particular-Programs.html"),
    AC_PROG_SED("AC_PROG_SED", "Particular-Programs.html"),
    AC_PROG_YACC("AC_PROG_YACC", "Particular-Programs.html"),
    AC_REPLACE_FNMATCH("AC_REPLACE_FNMATCH", "Particular-Functions.html"),
    AC_REPLACE_FUNCS("AC_REPLACE_FUNCS", "Generic-Functions.html"),
    AC_REQUIRE("AC_REQUIRE", "Prerequisite-Macros.html"),
    AC_REQUIRE_AUX_FILE("AC_REQUIRE_AUX_FILE", "Input.html"),
    AC_REQUIRE_CPP("AC_REQUIRE_CPP", "Language-Choice.html"),
    AC_REVISION("AC_REVISION", "Notices.html"),
    AC_RUN_IFELSE("AC_RUN_IFELSE", "Runtime.html"),
    AC_SEARCH_LIBS("AC_SEARCH_LIBS", "Libraries.html"),
    AC_STRUCT_DIRENT_D_INO("AC_STRUCT_DIRENT_D_INO", "Particular-Structures.html"),
    AC_STRUCT_DIRENT_D_TYPE("AC_STRUCT_DIRENT_D_TYPE", "Particular-Structures.html"),
    AC_STRUCT_ST_BLOCKS("AC_STRUCT_ST_BLOCKS", "Particular-Structures.html"),
    AC_STRUCT_TM("AC_STRUCT_TM", "Particular-Structures.html"),
    AC_STRUCT_TIMEZONE("AC_STRUCT_TIMEZONE", "Particular-Structures.html"),
    AC_SUBST("AC_SUBST", "Setting-Output-Variables.html"),
    AC_SUBST_FILE("AC_SUBST_FILE", "Setting-Output-Variables.html"),
    AC_SYS_INTERPRETER("AC_SYS_INTERPRETER", "System-Services.html"),
    AC_SYS_LARGEFILE("AC_SYS_LARGEFILE", "System-Services.html"),
    AC_SYS_LONG_FILE_NAMES("AC_SYS_LONG_FILE_NAMES", "System-Services.html"),
    AC_SYS_POSIX_TERMIOS("AC_SYS_POSIX_TERMIOS", "System-Services.html"),
    AC_TYPE_GETGROUPS("AC_TYPE_GETGROUPS", "Particular-Types.html"),
    AC_TYPE_INT8_T("AC_TYPE_INT8_T", "Particular-Types.html"),
    AC_TYPE_INT16_T("AC_TYPE_INT16_T", "Particular-Types.html"),
    AC_TYPE_INT32_T("AC_TYPE_INT32_T", "Particular-Types.html"),
    AC_TYPE_INT64_T("AC_TYPE_INT64_T", "Particular-Types.html"),
    AC_TYPE_INTMAX_T("AC_TYPE_INTMAX_T", "Particular-Types.html"),
    AC_TYPE_INTPTR_T("AC_TYPE_INTPTR_T", "Particular-Types.html"),
    AC_TYPE_LONG_DOUBLE("AC_TYPE_LONG_DOUBLE", "Particular-Types.html"),
    AC_TYPE_LONG_DOUBLE_WIDER("AC_TYPE_LONG_DOUBLE_WIDER", "Particular-Types.html"),
    AC_TYPE_LONG_LONG_INT("AC_TYPE_LONG_LONG_INT", "Particular-Types.html"),
    AC_TYPE_MBSTATE_T("AC_TYPE_MBSTATE_T", "Particular-Types.html"),
    AC_TYPE_MODE_T("AC_TYPE_MODE_T", "Particular-Types.html"),
    AC_TYPE_OFF_T("AC_TYPE_OFF_T", "Particular-Types.html"),
    AC_TYPE_PID_T("AC_TYPE_PID_T", "Particular-Types.html"),
    AC_TYPE_SIZE_T("AC_TYPE_SIZE_T", "Particular-Types.html"),
    AC_TYPE_SSIZE_T("AC_TYPE_SSIZE_T", "Particular-Types.html"),
    AC_TYPE_UID_T("AC_TYPE_UID_T", "Particular-Types.html"),
    AC_TYPE_UINT8_T("AC_TYPE_UINT8_T", "Particular-Types.html"),
    AC_TYPE_UINT16_T("AC_TYPE_UINT16_T", "Particular-Types.html"),
    AC_TYPE_UINT32_T("AC_TYPE_UINT32_T", "Particular-Types.html"),
    AC_TYPE_UINT64_T("AC_TYPE_UINT64_T", "Particular-Types.html"),
    AC_TYPE_UINTMAX_T("AC_TYPE_UINTMAX_T", "Particular-Types.html"),
    AC_TYPE_UINTPTR_T("AC_TYPE_UINTPTR_T", "Particular-Types.html"),
    AC_TYPE_UNSIGNED_LONG_LONG_INT("AC_TYPE_UNSIGNED_LONG_LONG_INT", "Particular-Types.html"),
    AC_USE_SYSTEM_EXTENSIONS("AC_USE_SYSTEM_EXTENSIONS", "Posix-Variants.html"),
    AC_WARNING("AC_WARNING", "Reporting-Messages.html"),
    AH_BOTTOM("AH_BOTTOM", "Autoheader-Macros.html"),
    AH_HEADER("AH_HEADER", "Configuration-Headers.html"),
    AH_TEMPLATE("AH_TEMPLATE", "Autoheader-Macros.html"),
    AH_TOP("AH_TOP", "Autoheader-Macros.html"),
    AH_VERBATIM("AH_VERBATIM", "Autoheader-Macros.html"),
    AM_INIT_AUTOMAKE("AM_INIT_AUTOMAKE", ""),
    AM_CONDITIONAL("AM_CONDITIONAL", ""),
    AS_BOURNE_COMPATIBLE("AS_BOURNE_COMPATIBLE", "Initialization-Macros.html"),
    AS_BOX("AS_BOX", "Common-Shell-Constructs.html"),
    AS_CASE("AS_CASE", "Common-Shell-Constructs.html"),
    AS_DIRNAME("AS_DIRNAME", "Common-Shell-Constructs.html"),
    AS_ECHO("AS_ECHO", "Common-Shell-Constructs.html"),
    AS_ECHO_N("AS_ECHO_N", "Common-Shell-Constructs.html"),
    AS_ESCAPE("AS_ESCAPE", "Common-Shell-Constructs.html"),
    AS_EXECUTABLE_P("AS_EXECUTABLE_P", "Common-Shell-Constructs.html"),
    AS_EXIT("AS_EXIT", "Common-Shell-Constructs.html"),
    AS_HELP_STRING("AS_HELP_STRING", "Pretty-Help-Strings.html"),
    AS_IF("AS_IF", "Common-Shell-Constructs.html"),
    AS_INIT("AS_INIT", "Initialization-Macros.html"),
    AS_INIT_GENERATED("AS_INIT_GENERATED", "Initialization-Macros.html"),
    AS_LINENO_PREPARE("AS_LINENO_PREPARE", "Initialization-Macros.html"),
    AS_LITERAL_IF("AS_LITERAL_IF", "Polymorphic-Variables.html"),
    AS_LITERAL_WORD_IF("AS_LITERAL_WORD_IF", "Polymorphic-Variables.html"),
    AS_ME_PREPARE("AS_ME_PREPARE", "Initialization-Macros.html"),
    AS_MESSAGE_FD("AS_MESSAGE_FD", "File-Descriptor-Macros.html"),
    AS_MESSAGE_LOG_FD("AS_MESSAGE_LOG_FD", "File-Descriptor-Macros.html"),
    AS_MKDIR_P("AS_MKDIR_P", "Common-Shell-Constructs.html"),
    AS_ORIGINAL_STDIN_FD("AS_ORIGINAL_STDIN_FD", "File-Descriptor-Macros.html"),
    AS_SET_CATFILE("AS_SET_CATFILE", "Common-Shell-Constructs.html"),
    AS_SET_STATUS("AS_SET_STATUS", "Common-Shell-Constructs.html"),
    AS_SHELL_SANITIZE("AS_SHELL_SANITIZE", "Initialization-Macros.html"),
    AS_TMPDIR("AS_TMPDIR", "Initialization-Macros.html"),
    AS_TR_CPP("AS_TR_CPP", "Common-Shell-Constructs.html"),
    AS_TR_SH("AS_TR_SH", "Common-Shell-Constructs.html"),
    AS_UNSET("AS_UNSET", "Common-Shell-Constructs.html"),
    AS_VAR_APPEND("AS_VAR_APPEND", "Polymorphic-Variables.html"),
    AS_VAR_ARITH("AS_VAR_ARITH", "Polymorphic-Variables.html"),
    AS_VAR_COPY("AS_VAR_COPY", "Polymorphic-Variables.html"),
    AS_VAR_IF("AS_VAR_IF", "Polymorphic-Variables.html"),
    AS_VAR_POPDEF("AS_VAR_POPDEF", "Polymorphic-Variables.html"),
    AS_VAR_PUSHDEF("AS_VAR_PUSHDEF", "Polymorphic-Variables.html"),
    AS_VAR_SET("AS_VAR_SET", "Polymorphic-Variables.html"),
    AS_VAR_SET_IF("AS_VAR_SET_IF", "Polymorphic-Variables.html"),
    AS_VAR_TEST_SET("AS_VAR_TEST_SET", "Polymorphic-Variables.html"),
    AS_VERSION_COMPARE("AS_VERSION_COMPARE", "Common-Shell-Constructs.html"),
    AU_ALIAS("AU_ALIAS", "Obsoleting-Macros.html"),
    AU_DEFUN("AU_DEFUN", "Obsoleting-Macros.html");

    private final String text;
    private final String docUrl;
    private final boolean obsolete;

    private AutoconfMacros(String text, String docUrl) {
        this.text = text;
        this.docUrl = docUrl;
        this.obsolete = false;
    }

    public String getText() {
        return this.text;
    }

    public String getDocUrl() {
        return this.docUrl;
    }

    public boolean isObsolete() {
        return this.obsolete;
    }
}
