/* Generated By:JavaCC: Do not edit this line. AutoconfParserConstants.java */
package org.netbeans.gnu.autotools.autoconf.lexer.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AutoconfParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int MRBRACKET = 5;
  /** RegularExpression Id. */
  int RBRACKET = 6;
  /** RegularExpression Id. */
  int BOOLEAN = 8;
  /** RegularExpression Id. */
  int BREAK = 9;
  /** RegularExpression Id. */
  int CASE = 10;
  /** RegularExpression Id. */
  int CHAR = 11;
  /** RegularExpression Id. */
  int CONTINUE = 12;
  /** RegularExpression Id. */
  int _DEFAULT = 13;
  /** RegularExpression Id. */
  int DO = 14;
  /** RegularExpression Id. */
  int DOUBLE = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int FINALLY = 18;
  /** RegularExpression Id. */
  int FLOAT = 19;
  /** RegularExpression Id. */
  int FOR = 20;
  /** RegularExpression Id. */
  int GOTO = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int INT = 23;
  /** RegularExpression Id. */
  int LONG = 24;
  /** RegularExpression Id. */
  int NULL = 25;
  /** RegularExpression Id. */
  int RETURN = 26;
  /** RegularExpression Id. */
  int SHORT = 27;
  /** RegularExpression Id. */
  int SWITCH = 28;
  /** RegularExpression Id. */
  int TRUE = 29;
  /** RegularExpression Id. */
  int TRY = 30;
  /** RegularExpression Id. */
  int VOID = 31;
  /** RegularExpression Id. */
  int WHILE = 32;
  /** RegularExpression Id. */
  int LPAREN = 33;
  /** RegularExpression Id. */
  int RPAREN = 34;
  /** RegularExpression Id. */
  int LBRACE = 35;
  /** RegularExpression Id. */
  int RBRACE = 36;
  /** RegularExpression Id. */
  int SEMICOLON = 37;
  /** RegularExpression Id. */
  int COMMA = 38;
  /** RegularExpression Id. */
  int DOT = 39;
  /** RegularExpression Id. */
  int AT = 40;
  /** RegularExpression Id. */
  int ASSIGN = 41;
  /** RegularExpression Id. */
  int LT = 42;
  /** RegularExpression Id. */
  int BANG = 43;
  /** RegularExpression Id. */
  int TILDE = 44;
  /** RegularExpression Id. */
  int HOOK = 45;
  /** RegularExpression Id. */
  int COLON = 46;
  /** RegularExpression Id. */
  int EQ = 47;
  /** RegularExpression Id. */
  int LE = 48;
  /** RegularExpression Id. */
  int GE = 49;
  /** RegularExpression Id. */
  int NE = 50;
  /** RegularExpression Id. */
  int SC_OR = 51;
  /** RegularExpression Id. */
  int SC_AND = 52;
  /** RegularExpression Id. */
  int INCR = 53;
  /** RegularExpression Id. */
  int DECR = 54;
  /** RegularExpression Id. */
  int PLUS = 55;
  /** RegularExpression Id. */
  int MINUS = 56;
  /** RegularExpression Id. */
  int STAR = 57;
  /** RegularExpression Id. */
  int SLASH = 58;
  /** RegularExpression Id. */
  int BIT_AND = 59;
  /** RegularExpression Id. */
  int BIT_OR = 60;
  /** RegularExpression Id. */
  int XOR = 61;
  /** RegularExpression Id. */
  int REM = 62;
  /** RegularExpression Id. */
  int LSHIFT = 63;
  /** RegularExpression Id. */
  int PLUSASSIGN = 64;
  /** RegularExpression Id. */
  int MINUSASSIGN = 65;
  /** RegularExpression Id. */
  int STARASSIGN = 66;
  /** RegularExpression Id. */
  int SLASHASSIGN = 67;
  /** RegularExpression Id. */
  int ANDASSIGN = 68;
  /** RegularExpression Id. */
  int ORASSIGN = 69;
  /** RegularExpression Id. */
  int XORASSIGN = 70;
  /** RegularExpression Id. */
  int REMASSIGN = 71;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 72;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 73;
  /** RegularExpression Id. */
  int ELLIPSIS = 74;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 75;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 76;
  /** RegularExpression Id. */
  int HEX_LITERAL = 77;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 78;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 79;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 80;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 81;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 82;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 83;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 84;
  /** RegularExpression Id. */
  int STRING_LITERAL = 85;
  /** RegularExpression Id. */
  int AC_PREREQ = 86;
  /** RegularExpression Id. */
  int AC_INIT = 87;
  /** RegularExpression Id. */
  int AC_COPYRIGHT = 88;
  /** RegularExpression Id. */
  int AC_REVISION = 89;
  /** RegularExpression Id. */
  int AC_CONFIG_SRCDIR = 90;
  /** RegularExpression Id. */
  int AC_CONFIG_AUX_DIR = 91;
  /** RegularExpression Id. */
  int AC_CONFIG_FILES = 92;
  /** RegularExpression Id. */
  int AC_CONFIG_MACRO_DIRS = 93;
  /** RegularExpression Id. */
  int AC_LANG = 94;
  /** RegularExpression Id. */
  int AC_PROG_CC = 95;
  /** RegularExpression Id. */
  int AC_PROG_CXX = 96;
  /** RegularExpression Id. */
  int AC_CONFIG_HEADERS = 97;
  /** RegularExpression Id. */
  int AM_INIT_AUTOMAKE = 98;
  /** RegularExpression Id. */
  int AC_CHECK_HEADERS = 99;
  /** RegularExpression Id. */
  int AM_CONDITIONAL = 100;
  /** RegularExpression Id. */
  int AC_CHECK_HEADER_STDBOOL = 101;
  /** RegularExpression Id. */
  int AC_TYPE_SIZE_T = 102;
  /** RegularExpression Id. */
  int AC_TYPE_UINT32_T = 103;
  /** RegularExpression Id. */
  int AC_TYPE_MODE_T = 104;
  /** RegularExpression Id. */
  int AC_FUNC_STRTOD = 105;
  /** RegularExpression Id. */
  int AC_CHECK_FUNCS = 106;
  /** RegularExpression Id. */
  int AC_MSG_ERROR = 107;
  /** RegularExpression Id. */
  int AC_CHECK_DECLS = 108;
  /** RegularExpression Id. */
  int AC_OUTPUT = 109;
  /** RegularExpression Id. */
  int AC_MACRO = 110;
  /** RegularExpression Id. */
  int AX_MACRO = 111;
  /** RegularExpression Id. */
  int AM_MACRO = 112;
  /** RegularExpression Id. */
  int IDENTIFIER = 113;
  /** RegularExpression Id. */
  int LETTER = 114;
  /** RegularExpression Id. */
  int PART_LETTER = 115;
  /** RegularExpression Id. */
  int TEXT = 116;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MCOMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "\"[\"",
    "\"[\"",
    "\"]\"",
    "\"]\"",
    "<token of kind 7>",
    "\"boolean\"",
    "\"break\"",
    "\"case\"",
    "\"char\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"false\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"int\"",
    "\"long\"",
    "\"null\"",
    "\"return\"",
    "\"short\"",
    "\"switch\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"...\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"AC_PREREQ\"",
    "\"AC_INIT\"",
    "\"AC_COPYRIGHT\"",
    "\"AC_REVISION\"",
    "\"AC_CONFIG_SRCDIR\"",
    "\"AC_CONFIG_AUX_DIR\"",
    "\"AC_CONFIG_FILES\"",
    "\"AC_CONFIG_MACRO_DIRS\"",
    "\"AC_LANG\"",
    "\"AC_PROG_CC\"",
    "\"AC_PROG_CXX\"",
    "\"AC_CONFIG_HEADERS\"",
    "\"AM_INIT_AUTOMAKE\"",
    "\"AC_CHECK_HEADERS\"",
    "\"AM_CONDITIONAL\"",
    "\"AC_CHECK_HEADER_STDBOOL\"",
    "\"AC_TYPE_SIZE_T\"",
    "\"AC_TYPE_UINT32_T\"",
    "\"AC_TYPE_MODE_T\"",
    "\"AC_FUNC_STRTOD\"",
    "\"AC_CHECK_FUNCS\"",
    "\"AC_MSG_ERROR\"",
    "\"AC_CHECK_DECLS\"",
    "\"AC_OUTPUT\"",
    "<AC_MACRO>",
    "<AX_MACRO>",
    "<AM_MACRO>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<TEXT>",
  };

}
