/* Generated By:JavaCC: Do not edit this line. AutoconfParserTokenManager.java */
package org.netbeans.gnu.autotools.autoconf.lexer.javacc;

/** Token Manager. */
public class AutoconfParserTokenManager implements AutoconfParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1000000000L) != 0L || (active1 & 0x80L) != 0L)
            return 10;
         if ((active0 & 0xffffff8L) != 0L || (active1 & 0x7ff00L) != 0L)
         {
            jjmatchedKind = 94;
            return 34;
         }
         return -1;
      case 1:
         if ((active0 & 0x20600L) != 0L)
            return 34;
         if ((active0 & 0xffdf9f8L) != 0L || (active1 & 0x7ff00L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 94;
               jjmatchedPos = 1;
            }
            return 34;
         }
         return -1;
      case 2:
         if ((active0 & 0x2048000L) != 0L)
            return 34;
         if ((active0 & 0xdf97df8L) != 0L || (active1 & 0x7ff00L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 2;
            return 34;
         }
         return -1;
      case 3:
         if ((active0 & 0x5190860L) != 0L)
            return 34;
         if ((active0 & 0x8e07598L) != 0L || (active1 & 0x7ff00L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 3;
            return 34;
         }
         return -1;
      case 4:
         if ((active0 & 0x8405010L) != 0L)
            return 34;
         if ((active0 & 0xa02588L) != 0L || (active1 & 0x7ff00L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 4;
            return 34;
         }
         return -1;
      case 5:
         if ((active0 & 0xa00400L) != 0L)
            return 34;
         if ((active0 & 0x2188L) != 0L || (active1 & 0x7ff00L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 5;
            return 34;
         }
         return -1;
      case 6:
         if ((active0 & 0x2108L) != 0L || (active1 & 0x10200L) != 0L)
            return 34;
         if ((active0 & 0x80L) != 0L || (active1 & 0x6fd00L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 6;
            return 34;
         }
         return -1;
      case 7:
         if ((active0 & 0x80L) != 0L)
            return 34;
         if ((active1 & 0x6fd00L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 7;
            return 34;
         }
         return -1;
      case 8:
         if ((active1 & 0x100L) != 0L)
            return 34;
         if ((active1 & 0x6fc00L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 8;
            return 34;
         }
         return -1;
      case 9:
         if ((active1 & 0x20000L) != 0L)
            return 34;
         if ((active1 & 0x4fc00L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 9;
            return 34;
         }
         return -1;
      case 10:
         if ((active1 & 0x40800L) != 0L)
            return 34;
         if ((active1 & 0xf400L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 10;
            return 34;
         }
         return -1;
      case 11:
         if ((active1 & 0x400L) != 0L)
            return 34;
         if ((active1 & 0xf000L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 11;
            return 34;
         }
         return -1;
      case 12:
         if ((active1 & 0xf000L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 12;
            return 34;
         }
         return -1;
      case 13:
         if ((active1 & 0xf000L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 13;
            return 34;
         }
         return -1;
      case 14:
         if ((active1 & 0x4000L) != 0L)
            return 34;
         if ((active1 & 0xb000L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 14;
            return 34;
         }
         return -1;
      case 15:
         if ((active1 & 0x1000L) != 0L)
            return 34;
         if ((active1 & 0xa000L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 15;
            return 34;
         }
         return -1;
      case 16:
         if ((active1 & 0x2000L) != 0L)
            return 34;
         if ((active1 & 0x8000L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 16;
            return 34;
         }
         return -1;
      case 17:
         if ((active1 & 0x8000L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 17;
            return 34;
         }
         return -1;
      case 18:
         if ((active1 & 0x8000L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 18;
            return 34;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 40;
         return jjMoveStringLiteralDfa1_0(0x800000000000L, 0x0L);
      case 37:
         jjmatchedKind = 59;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10L);
      case 38:
         jjmatchedKind = 56;
         return jjMoveStringLiteralDfa1_0(0x2000000000000L, 0x2L);
      case 40:
         return jjStopAtPos(0, 28);
      case 41:
         return jjStopAtPos(0, 29);
      case 42:
         jjmatchedKind = 54;
         return jjMoveStringLiteralDfa1_0(0x8000000000000000L, 0x0L);
      case 43:
         jjmatchedKind = 52;
         return jjMoveStringLiteralDfa1_0(0x2004000000000000L, 0x0L);
      case 44:
         return jjStopAtPos(0, 35);
      case 45:
         jjmatchedKind = 53;
         return jjMoveStringLiteralDfa1_0(0x4008000000000000L, 0x0L);
      case 46:
         jjmatchedKind = 36;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80L);
      case 47:
         jjmatchedKind = 55;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1L);
      case 58:
         return jjStopAtPos(0, 43);
      case 59:
         return jjStopAtPos(0, 34);
      case 60:
         jjmatchedKind = 39;
         return jjMoveStringLiteralDfa1_0(0x1000200000000000L, 0x20L);
      case 61:
         jjmatchedKind = 38;
         return jjMoveStringLiteralDfa1_0(0x100000000000L, 0x0L);
      case 62:
         return jjMoveStringLiteralDfa1_0(0x400000000000L, 0x40L);
      case 63:
         return jjStopAtPos(0, 42);
      case 64:
         return jjStopAtPos(0, 37);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x7ff00L);
      case 91:
         return jjStopAtPos(0, 32);
      case 93:
         return jjStopAtPos(0, 33);
      case 94:
         jjmatchedKind = 58;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x18L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0xe0L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x700L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x800L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0xf000L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x10000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x60000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x80000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x100000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x200000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0xc00000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x3000000L, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x4000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x8000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 30);
      case 124:
         jjmatchedKind = 57;
         return jjMoveStringLiteralDfa1_0(0x1000000000000L, 0x4L);
      case 125:
         return jjStopAtPos(0, 31);
      case 126:
         return jjStopAtPos(0, 41);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStopAtPos(1, 49);
         break;
      case 43:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(1, 50);
         break;
      case 45:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(1, 51);
         break;
      case 46:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x80L);
      case 60:
         if ((active0 & 0x1000000000000000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x20L);
      case 61:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 44);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStopAtPos(1, 45);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStopAtPos(1, 46);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStopAtPos(1, 47);
         else if ((active0 & 0x2000000000000000L) != 0L)
            return jjStopAtPos(1, 61);
         else if ((active0 & 0x4000000000000000L) != 0L)
            return jjStopAtPos(1, 62);
         else if ((active0 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(1, 63);
         else if ((active1 & 0x1L) != 0L)
            return jjStopAtPos(1, 64);
         else if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(1, 65);
         else if ((active1 & 0x4L) != 0L)
            return jjStopAtPos(1, 66);
         else if ((active1 & 0x8L) != 0L)
            return jjStopAtPos(1, 67);
         else if ((active1 & 0x10L) != 0L)
            return jjStopAtPos(1, 68);
         break;
      case 62:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40L);
      case 67:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x7ff00L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x1020L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x200100L, active1, 0L);
      case 102:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(1, 17, 34);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x8400040L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x4800L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L, active1, 0L);
      case 111:
         if ((active0 & 0x200L) != 0L)
         {
            jjmatchedKind = 9;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x4098488L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x3000010L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L, active1, 0L);
      case 124:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(1, 48);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 46:
         if ((active1 & 0x80L) != 0L)
            return jjStopAtPos(2, 71);
         break;
      case 61:
         if ((active1 & 0x20L) != 0L)
            return jjStopAtPos(2, 69);
         else if ((active1 & 0x40L) != 0L)
            return jjStopAtPos(2, 70);
         break;
      case 95:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x7ff00L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x10L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0xc800000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x101000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x82080L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x404008L, active1, 0L);
      case 114:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(2, 15, 34);
         break;
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x820L, active1, 0L);
      case 116:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(2, 18, 34);
         return jjMoveStringLiteralDfa3_0(active0, 0x210000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000400L, active1, 0L);
      case 121:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(2, 25, 34);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0xf400L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x200L);
      case 76:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x10000L);
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x60100L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x800L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x6110L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x400L, active1, 0L);
      case 100:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 26, 34);
         break;
      case 101:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(3, 5, 34);
         else if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 34);
         else if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 34);
         break;
      case 103:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 34);
         break;
      case 108:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 34);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000008L, active1, 0L);
      case 111:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 16, 34);
         break;
      case 114:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(3, 6, 34);
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x800080L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x10000L);
      case 69:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x800L);
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x200L);
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0xf400L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x60100L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L, active1, 0L);
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 12, 34);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 34);
         return jjMoveStringLiteralDfa5_0(active0, 0x8L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x80L, active1, 0L);
      case 107:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 34);
         break;
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x2400L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000L, active1, 0L);
      case 116:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 14, 34);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(4, 22, 34);
         break;
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x100L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x100L);
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x200L);
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x1f000L);
      case 79:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x60000L);
      case 80:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x400L);
      case 86:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x800L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x8L, active1, 0L);
      case 101:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(5, 10, 34);
         break;
      case 104:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 23, 34);
         break;
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x2100L, active1, 0L);
      case 110:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(5, 21, 34);
         return jjMoveStringLiteralDfa6_0(active0, 0x80L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 70:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0xf000L);
      case 71:
         if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(6, 80, 34);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x60000L);
      case 73:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x800L);
      case 82:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x100L);
      case 84:
         if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(6, 73, 34);
         break;
      case 89:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x400L);
      case 110:
         if ((active0 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(6, 3, 34);
         break;
      case 116:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(6, 8, 34);
         break;
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x80L, active1, 0L);
      case 121:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(6, 13, 34);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x100L);
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0xf000L);
      case 82:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x400L);
      case 83:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x800L);
      case 95:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x60000L);
      case 101:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(7, 7, 34);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, 0L, active1);
      return 8;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa9_0(active1, 0x60000L);
      case 71:
         return jjMoveStringLiteralDfa9_0(active1, 0xf000L);
      case 73:
         return jjMoveStringLiteralDfa9_0(active1, 0xc00L);
      case 81:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(8, 72, 34);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, 0L, active1);
}
private int jjMoveStringLiteralDfa9_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(7, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, 0L, active1);
      return 9;
   }
   switch(curChar)
   {
      case 67:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(9, 81, 34);
         break;
      case 71:
         return jjMoveStringLiteralDfa10_0(active1, 0x400L);
      case 79:
         return jjMoveStringLiteralDfa10_0(active1, 0x800L);
      case 88:
         return jjMoveStringLiteralDfa10_0(active1, 0x40000L);
      case 95:
         return jjMoveStringLiteralDfa10_0(active1, 0xf000L);
      default :
         break;
   }
   return jjStartNfa_0(8, 0L, active1);
}
private int jjMoveStringLiteralDfa10_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(8, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, 0L, active1);
      return 10;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa11_0(active1, 0x2000L);
      case 70:
         return jjMoveStringLiteralDfa11_0(active1, 0x4000L);
      case 72:
         return jjMoveStringLiteralDfa11_0(active1, 0x400L);
      case 77:
         return jjMoveStringLiteralDfa11_0(active1, 0x8000L);
      case 78:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(10, 75, 34);
         break;
      case 83:
         return jjMoveStringLiteralDfa11_0(active1, 0x1000L);
      case 88:
         if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(10, 82, 34);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, 0L, active1);
}
private int jjMoveStringLiteralDfa11_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(9, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, 0L, active1);
      return 11;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa12_0(active1, 0x8000L);
      case 73:
         return jjMoveStringLiteralDfa12_0(active1, 0x4000L);
      case 82:
         return jjMoveStringLiteralDfa12_0(active1, 0x1000L);
      case 84:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(11, 74, 34);
         break;
      case 85:
         return jjMoveStringLiteralDfa12_0(active1, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(10, 0L, active1);
}
private int jjMoveStringLiteralDfa12_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(10, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, 0L, active1);
      return 12;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa13_0(active1, 0x9000L);
      case 76:
         return jjMoveStringLiteralDfa13_0(active1, 0x4000L);
      case 88:
         return jjMoveStringLiteralDfa13_0(active1, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(11, 0L, active1);
}
private int jjMoveStringLiteralDfa13_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(11, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, 0L, active1);
      return 13;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa14_0(active1, 0x1000L);
      case 69:
         return jjMoveStringLiteralDfa14_0(active1, 0x4000L);
      case 82:
         return jjMoveStringLiteralDfa14_0(active1, 0x8000L);
      case 95:
         return jjMoveStringLiteralDfa14_0(active1, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(12, 0L, active1);
}
private int jjMoveStringLiteralDfa14_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(12, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, 0L, active1);
      return 14;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa15_0(active1, 0x2000L);
      case 73:
         return jjMoveStringLiteralDfa15_0(active1, 0x1000L);
      case 79:
         return jjMoveStringLiteralDfa15_0(active1, 0x8000L);
      case 83:
         if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(14, 78, 34);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, 0L, active1);
}
private int jjMoveStringLiteralDfa15_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(13, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, 0L, active1);
      return 15;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa16_0(active1, 0x2000L);
      case 82:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(15, 76, 34);
         break;
      case 95:
         return jjMoveStringLiteralDfa16_0(active1, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(14, 0L, active1);
}
private int jjMoveStringLiteralDfa16_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(14, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, 0L, active1);
      return 16;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa17_0(active1, 0x8000L);
      case 82:
         if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(16, 77, 34);
         break;
      default :
         break;
   }
   return jjStartNfa_0(15, 0L, active1);
}
private int jjMoveStringLiteralDfa17_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(15, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, 0L, active1);
      return 17;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa18_0(active1, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(16, 0L, active1);
}
private int jjMoveStringLiteralDfa18_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(16, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, 0L, active1);
      return 18;
   }
   switch(curChar)
   {
      case 82:
         return jjMoveStringLiteralDfa19_0(active1, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(17, 0L, active1);
}
private int jjMoveStringLiteralDfa19_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(17, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, 0L, active1);
      return 19;
   }
   switch(curChar)
   {
      case 83:
         if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(19, 79, 34);
         break;
      default :
         break;
   }
   return jjStartNfa_0(18, 0L, active1);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 67;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 6);
                  else if ((0x100003600L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                  }
                  else if (curChar == 36)
                  {
                     if (kind > 94)
                        kind = 94;
                     jjCheckNAdd(34);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(7, 9);
                  else if (curChar == 39)
                     jjAddStates(10, 11);
                  else if (curChar == 46)
                     jjCheckNAdd(10);
                  else if (curChar == 35)
                  {
                     if (kind > 2)
                        kind = 2;
                     jjCheckNAddStates(12, 14);
                  }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 83)
                        kind = 83;
                     jjCheckNAddTwoStates(7, 8);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 83)
                        kind = 83;
                     jjCheckNAddStates(15, 19);
                  }
                  break;
               case 1:
                  if (curChar != 35)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddStates(12, 14);
                  break;
               case 2:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddStates(12, 14);
                  break;
               case 3:
                  if ((0x2400L & l) != 0L && kind > 2)
                     kind = 2;
                  break;
               case 4:
                  if (curChar == 10 && kind > 2)
                     kind = 2;
                  break;
               case 5:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 83)
                     kind = 83;
                  jjCheckNAddTwoStates(7, 8);
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 83)
                     kind = 83;
                  jjCheckNAddTwoStates(7, 8);
                  break;
               case 9:
                  if (curChar == 46)
                     jjCheckNAdd(10);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddStates(20, 22);
                  break;
               case 12:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(13);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddTwoStates(13, 14);
                  break;
               case 15:
                  if (curChar == 39)
                     jjAddStates(10, 11);
                  break;
               case 16:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAdd(17);
                  break;
               case 17:
                  if (curChar == 39 && kind > 92)
                     kind = 92;
                  break;
               case 19:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAdd(17);
                  break;
               case 20:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(21, 17);
                  break;
               case 21:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(17);
                  break;
               case 22:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 23:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(21);
                  break;
               case 24:
                  if (curChar == 34)
                     jjCheckNAddStates(7, 9);
                  break;
               case 25:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 27:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 28:
                  if (curChar == 34 && kind > 93)
                     kind = 93;
                  break;
               case 29:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(23, 26);
                  break;
               case 30:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 31:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 32:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(30);
                  break;
               case 33:
                  if (curChar != 36)
                     break;
                  if (kind > 94)
                     kind = 94;
                  jjCheckNAdd(34);
                  break;
               case 34:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 94)
                     kind = 94;
                  jjCheckNAdd(34);
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 6);
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(27, 29);
                  break;
               case 38:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(39);
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(39, 14);
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(40, 41);
                  break;
               case 42:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(43);
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddTwoStates(43, 14);
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(44, 45);
                  break;
               case 45:
                  if (curChar != 46)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddStates(30, 32);
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddStates(30, 32);
                  break;
               case 48:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(49);
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddTwoStates(49, 14);
                  break;
               case 50:
                  if (curChar != 48)
                     break;
                  if (kind > 83)
                     kind = 83;
                  jjCheckNAddStates(15, 19);
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 83)
                     kind = 83;
                  jjCheckNAddTwoStates(52, 8);
                  break;
               case 53:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 83)
                     kind = 83;
                  jjCheckNAddTwoStates(53, 8);
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(33, 34);
                  break;
               case 56:
                  if (curChar == 46)
                     jjCheckNAdd(57);
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(57, 58);
                  break;
               case 59:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(60);
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddTwoStates(60, 14);
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(35, 37);
                  break;
               case 63:
                  if (curChar == 46)
                     jjCheckNAdd(64);
                  break;
               case 65:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(66);
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddTwoStates(66, 14);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 34:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 94)
                     kind = 94;
                  jjCheckNAdd(34);
                  break;
               case 2:
                  if (kind > 2)
                     kind = 2;
                  jjAddStates(12, 14);
                  break;
               case 8:
                  if ((0x100000001000L & l) != 0L && kind > 83)
                     kind = 83;
                  break;
               case 11:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(38, 39);
                  break;
               case 14:
                  if ((0x5000000050L & l) != 0L && kind > 87)
                     kind = 87;
                  break;
               case 16:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(17);
                  break;
               case 18:
                  if (curChar == 92)
                     jjAddStates(40, 42);
                  break;
               case 19:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAdd(17);
                  break;
               case 25:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 26:
                  if (curChar == 92)
                     jjAddStates(43, 45);
                  break;
               case 27:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 37:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(46, 47);
                  break;
               case 41:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(48, 49);
                  break;
               case 47:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(50, 51);
                  break;
               case 51:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(52);
                  break;
               case 52:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 83)
                     kind = 83;
                  jjCheckNAddTwoStates(52, 8);
                  break;
               case 54:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAddTwoStates(55, 56);
                  break;
               case 55:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(55, 56);
                  break;
               case 57:
                  if ((0x7e0000007eL & l) != 0L)
                     jjAddStates(52, 53);
                  break;
               case 58:
                  if ((0x1000000010000L & l) != 0L)
                     jjAddStates(54, 55);
                  break;
               case 61:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(62);
                  break;
               case 62:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(35, 37);
                  break;
               case 64:
                  if ((0x1000000010000L & l) != 0L)
                     jjAddStates(56, 57);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjAddStates(12, 14);
                  break;
               case 16:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 25:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(7, 9);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 67 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   36, 37, 14, 40, 41, 44, 45, 25, 26, 28, 16, 18, 2, 3, 5, 51, 
   53, 8, 54, 61, 10, 11, 14, 25, 26, 30, 28, 36, 37, 14, 46, 47, 
   14, 55, 56, 62, 63, 64, 12, 13, 19, 20, 22, 27, 29, 31, 38, 39, 
   42, 43, 48, 49, 57, 58, 59, 60, 65, 66, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, "\142\157\157\154\145\141\156", "\142\162\145\141\153", 
"\143\141\163\145", "\143\150\141\162", "\143\157\156\164\151\156\165\145", 
"\144\145\146\141\165\154\164", "\144\157", "\144\157\165\142\154\145", "\145\154\163\145", 
"\146\141\154\163\145", "\146\151\156\141\154\154\171", "\146\154\157\141\164", "\146\157\162", 
"\147\157\164\157", "\151\146", "\151\156\164", "\154\157\156\147", "\156\165\154\154", 
"\162\145\164\165\162\156", "\163\150\157\162\164", "\163\167\151\164\143\150", "\164\162\165\145", 
"\164\162\171", "\166\157\151\144", "\167\150\151\154\145", "\50", "\51", "\173", "\175", 
"\133", "\135", "\73", "\54", "\56", "\100", "\75", "\74", "\41", "\176", "\77", 
"\72", "\75\75", "\74\75", "\76\75", "\41\75", "\174\174", "\46\46", "\53\53", 
"\55\55", "\53", "\55", "\52", "\57", "\46", "\174", "\136", "\45", "\74\74", "\53\75", 
"\55\75", "\52\75", "\57\75", "\46\75", "\174\75", "\136\75", "\45\75", "\74\74\75", 
"\76\76\75", "\56\56\56", "\101\103\137\120\122\105\122\105\121", 
"\101\103\137\111\116\111\124", "\101\103\137\103\117\120\131\122\111\107\110\124", 
"\101\103\137\122\105\126\111\123\111\117\116", "\101\103\137\103\117\116\106\111\107\137\123\122\103\104\111\122", 
"\101\103\137\103\117\116\106\111\107\137\101\125\130\137\104\111\122", "\101\103\137\103\117\116\106\111\107\137\106\111\114\105\123", 
"\101\103\137\103\117\116\106\111\107\137\115\101\103\122\117\137\104\111\122\123", "\101\103\137\114\101\116\107", "\101\103\137\120\122\117\107\137\103\103", 
"\101\103\137\120\122\117\107\137\103\130\130", null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
protected JavaCharStream input_stream;
private final int[] jjrounds = new int[67];
private final int[] jjstateSet = new int[134];
protected char curChar;
/** Constructor. */
public AutoconfParserTokenManager(JavaCharStream stream){
   if (JavaCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public AutoconfParserTokenManager(JavaCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(JavaCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 67; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(JavaCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 97)
   {
      jjmatchedKind = 97;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
         matchedToken = jjFillToken();
         return matchedToken;
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
