/* Generated By:JavaCC: Do not edit this line. AutoconfParserConstants.java */
package org.netbeans.gnu.autotools.autoconf.lexer.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AutoconfParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int BOOLEAN = 3;
  /** RegularExpression Id. */
  int BREAK = 4;
  /** RegularExpression Id. */
  int CASE = 5;
  /** RegularExpression Id. */
  int CHAR = 6;
  /** RegularExpression Id. */
  int CONTINUE = 7;
  /** RegularExpression Id. */
  int _DEFAULT = 8;
  /** RegularExpression Id. */
  int DO = 9;
  /** RegularExpression Id. */
  int DOUBLE = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int FALSE = 12;
  /** RegularExpression Id. */
  int FINALLY = 13;
  /** RegularExpression Id. */
  int FLOAT = 14;
  /** RegularExpression Id. */
  int FOR = 15;
  /** RegularExpression Id. */
  int GOTO = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int INT = 18;
  /** RegularExpression Id. */
  int LONG = 19;
  /** RegularExpression Id. */
  int NULL = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int SHORT = 22;
  /** RegularExpression Id. */
  int SWITCH = 23;
  /** RegularExpression Id. */
  int TRUE = 24;
  /** RegularExpression Id. */
  int TRY = 25;
  /** RegularExpression Id. */
  int VOID = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 28;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 29;
  /** RegularExpression Id. */
  int HEX_LITERAL = 30;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 31;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 32;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 33;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 34;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 35;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 36;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 37;
  /** RegularExpression Id. */
  int STRING_LITERAL = 38;
  /** RegularExpression Id. */
  int IDENTIFIER = 39;
  /** RegularExpression Id. */
  int LETTER = 40;
  /** RegularExpression Id. */
  int PART_LETTER = 41;
  /** RegularExpression Id. */
  int LPAREN = 42;
  /** RegularExpression Id. */
  int RPAREN = 43;
  /** RegularExpression Id. */
  int LBRACE = 44;
  /** RegularExpression Id. */
  int RBRACE = 45;
  /** RegularExpression Id. */
  int LBRACKET = 46;
  /** RegularExpression Id. */
  int RBRACKET = 47;
  /** RegularExpression Id. */
  int SEMICOLON = 48;
  /** RegularExpression Id. */
  int COMMA = 49;
  /** RegularExpression Id. */
  int DOT = 50;
  /** RegularExpression Id. */
  int AT = 51;
  /** RegularExpression Id. */
  int ASSIGN = 52;
  /** RegularExpression Id. */
  int LT = 53;
  /** RegularExpression Id. */
  int BANG = 54;
  /** RegularExpression Id. */
  int TILDE = 55;
  /** RegularExpression Id. */
  int HOOK = 56;
  /** RegularExpression Id. */
  int COLON = 57;
  /** RegularExpression Id. */
  int EQ = 58;
  /** RegularExpression Id. */
  int LE = 59;
  /** RegularExpression Id. */
  int GE = 60;
  /** RegularExpression Id. */
  int NE = 61;
  /** RegularExpression Id. */
  int SC_OR = 62;
  /** RegularExpression Id. */
  int SC_AND = 63;
  /** RegularExpression Id. */
  int INCR = 64;
  /** RegularExpression Id. */
  int DECR = 65;
  /** RegularExpression Id. */
  int PLUS = 66;
  /** RegularExpression Id. */
  int MINUS = 67;
  /** RegularExpression Id. */
  int STAR = 68;
  /** RegularExpression Id. */
  int SLASH = 69;
  /** RegularExpression Id. */
  int BIT_AND = 70;
  /** RegularExpression Id. */
  int BIT_OR = 71;
  /** RegularExpression Id. */
  int XOR = 72;
  /** RegularExpression Id. */
  int REM = 73;
  /** RegularExpression Id. */
  int LSHIFT = 74;
  /** RegularExpression Id. */
  int PLUSASSIGN = 75;
  /** RegularExpression Id. */
  int MINUSASSIGN = 76;
  /** RegularExpression Id. */
  int STARASSIGN = 77;
  /** RegularExpression Id. */
  int SLASHASSIGN = 78;
  /** RegularExpression Id. */
  int ANDASSIGN = 79;
  /** RegularExpression Id. */
  int ORASSIGN = 80;
  /** RegularExpression Id. */
  int XORASSIGN = 81;
  /** RegularExpression Id. */
  int REMASSIGN = 82;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 83;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 84;
  /** RegularExpression Id. */
  int ELLIPSIS = 85;
  /** RegularExpression Id. */
  int TEXT = 86;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "\"boolean\"",
    "\"break\"",
    "\"case\"",
    "\"char\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"false\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"int\"",
    "\"long\"",
    "\"null\"",
    "\"return\"",
    "\"short\"",
    "\"switch\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"...\"",
    "<TEXT>",
  };

}
