/* Generated By:JavaCC: Do not edit this line. AutoconfParserTokenManager.java */
package org.netbeans.gnu.autotools.autoconf.parser.javacc;
import java.io.*;
import java.util.*;

/** Token Manager. */
public class AutoconfParserTokenManager implements AutoconfParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xffffff80L) != 0L || (active1 & 0x7bfffe40007ff000L) != 0L || (active2 & 0x1fL) != 0L)
         {
            jjmatchedKind = 99;
            return 36;
         }
         if ((active0 & 0x1000000000L) != 0L)
            return 69;
         if ((active0 & 0x10000000000L) != 0L || (active1 & 0x800L) != 0L)
            return 9;
         return -1;
      case 1:
         if ((active0 & 0x206000L) != 0L)
            return 36;
         if ((active0 & 0xffdf9f80L) != 0L || (active1 & 0x7bfffe40007ff000L) != 0L || (active2 & 0x1fL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 99;
               jjmatchedPos = 1;
            }
            return 36;
         }
         return -1;
      case 2:
         if ((active0 & 0x20480000L) != 0L || (active1 & 0x40000000000000L) != 0L)
            return 36;
         if ((active0 & 0xdf97df80L) != 0L || (active1 & 0x7bbffe40007ff000L) != 0L || (active2 & 0x1fL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 99;
               jjmatchedPos = 2;
            }
            return 36;
         }
         return -1;
      case 3:
         if ((active0 & 0x8e075980L) != 0L || (active1 & 0x7bfffe40007ff000L) != 0L || (active2 & 0x1dL) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 3;
            return 36;
         }
         if ((active0 & 0x51908600L) != 0L)
            return 36;
         return -1;
      case 4:
         if ((active0 & 0x84050100L) != 0L)
            return 36;
         if ((active0 & 0xa025880L) != 0L || (active1 & 0x29fffe40007ff000L) != 0L || (active2 & 0x1dL) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 99;
               jjmatchedPos = 4;
            }
            return 36;
         }
         return -1;
      case 5:
         if ((active0 & 0xa004000L) != 0L)
            return 36;
         if ((active0 & 0x21880L) != 0L || (active1 & 0x9dfbe40007ff000L) != 0L || (active2 & 0x5L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 5;
            return 36;
         }
         return -1;
      case 6:
         if ((active0 & 0x800L) != 0L || (active1 & 0x1ddb040006fd000L) != 0L || (active2 & 0x1L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 6;
            return 36;
         }
         if ((active0 & 0x21080L) != 0L || (active1 & 0x102000L) != 0L)
            return 36;
         return -1;
      case 7:
         if ((active0 & 0x800L) != 0L)
            return 36;
         if ((active1 & 0x15d9000006fd000L) != 0L || (active2 & 0x1L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 7;
            return 36;
         }
         return -1;
      case 8:
         if ((active1 & 0x1000L) != 0L)
            return 36;
         if ((active1 & 0x1451000006fc000L) != 0L || (active2 & 0x1L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 8;
            return 36;
         }
         return -1;
      case 9:
         if ((active1 & 0x200000L) != 0L)
            return 36;
         if ((active1 & 0x1010000004fc000L) != 0L || (active2 & 0x1L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 9;
            return 36;
         }
         return -1;
      case 10:
         if ((active1 & 0x408000L) != 0L)
            return 36;
         if ((active1 & 0x10000000f4000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 10;
            return 36;
         }
         return -1;
      case 11:
         if ((active1 & 0x4000L) != 0L)
            return 36;
         if ((active1 & 0x10000000f0000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 11;
            return 36;
         }
         return -1;
      case 12:
         if ((active1 & 0xf0000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 12;
            return 36;
         }
         return -1;
      case 13:
         if ((active1 & 0xf0000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 13;
            return 36;
         }
         return -1;
      case 14:
         if ((active1 & 0x40000L) != 0L)
            return 36;
         if ((active1 & 0xb0000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 14;
            return 36;
         }
         return -1;
      case 15:
         if ((active1 & 0x10000L) != 0L)
            return 36;
         if ((active1 & 0xa0000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 15;
            return 36;
         }
         return -1;
      case 16:
         if ((active1 & 0x20000L) != 0L)
            return 36;
         if ((active1 & 0x80000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 16;
            return 36;
         }
         return -1;
      case 17:
         if ((active1 & 0x80000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 17;
            return 36;
         }
         return -1;
      case 18:
         if ((active1 & 0x80000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 18;
            return 36;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1, long active2)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 26:
         return jjStopAtPos(0, 103);
      case 33:
         jjmatchedKind = 44;
         return jjMoveStringLiteralDfa1_0(0x8000000000000L, 0x0L, 0x0L);
      case 37:
         jjmatchedKind = 63;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100L, 0x0L);
      case 38:
         jjmatchedKind = 60;
         return jjMoveStringLiteralDfa1_0(0x20000000000000L, 0x20L, 0x0L);
      case 40:
         return jjStopAtPos(0, 32);
      case 41:
         return jjStopAtPos(0, 33);
      case 42:
         jjmatchedKind = 58;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8L, 0x0L);
      case 43:
         jjmatchedKind = 56;
         return jjMoveStringLiteralDfa1_0(0x40000000000000L, 0x2L, 0x0L);
      case 44:
         return jjStopAtPos(0, 39);
      case 45:
         jjmatchedKind = 57;
         return jjMoveStringLiteralDfa1_0(0x80000000000000L, 0x4L, 0x0L);
      case 46:
         jjmatchedKind = 40;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800L, 0x0L);
      case 47:
         jjmatchedKind = 59;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10L, 0x0L);
      case 58:
         return jjStopAtPos(0, 47);
      case 59:
         return jjStopAtPos(0, 38);
      case 60:
         jjmatchedKind = 43;
         return jjMoveStringLiteralDfa1_0(0x2000000000000L, 0x201L, 0x0L);
      case 61:
         jjmatchedKind = 42;
         return jjMoveStringLiteralDfa1_0(0x1000000000000L, 0x0L, 0x0L);
      case 62:
         jjmatchedKind = 104;
         return jjMoveStringLiteralDfa1_0(0x4000000000000L, 0x8000000000000400L, 0x0L);
      case 63:
         return jjStopAtPos(0, 46);
      case 64:
         return jjStopAtPos(0, 41);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x7ff000L, 0x0L);
      case 91:
         return jjStartNfaWithStates_0(0, 36, 69);
      case 93:
         return jjStopAtPos(0, 37);
      case 94:
         jjmatchedKind = 62;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80L, 0x0L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000000000L, 0x4L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x180L, 0x4000000000000000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0xe00L, 0x20000000000000L, 0x10L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x7000L, 0x0L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x8000L, 0x280000000000000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0xf0000L, 0x400000000000L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x100000L, 0x0L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x600000L, 0x140020000000000L, 0x1L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x800000L, 0x0L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x1000000L, 0x2000000000000L, 0x2L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x384000000000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x2000000L, 0x0L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0xc000000L, 0x2011040000000000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x30000000L, 0x1804000000000000L, 0x8L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x40000000L, 0x8000000000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x80000000L, 0x0L, 0x0L);
      case 123:
         return jjStopAtPos(0, 34);
      case 124:
         jjmatchedKind = 61;
         return jjMoveStringLiteralDfa1_0(0x10000000000000L, 0x40L, 0x0L);
      case 125:
         return jjStopAtPos(0, 35);
      case 126:
         return jjStopAtPos(0, 45);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStopAtPos(1, 53);
         break;
      case 43:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStopAtPos(1, 54);
         break;
      case 45:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStopAtPos(1, 55);
         break;
      case 46:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800L, active2, 0L);
      case 60:
         if ((active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x200L, active2, 0L);
      case 61:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(1, 48);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStopAtPos(1, 49);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(1, 50);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(1, 51);
         else if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(1, 65);
         else if ((active1 & 0x4L) != 0L)
            return jjStopAtPos(1, 66);
         else if ((active1 & 0x8L) != 0L)
            return jjStopAtPos(1, 67);
         else if ((active1 & 0x10L) != 0L)
            return jjStopAtPos(1, 68);
         else if ((active1 & 0x20L) != 0L)
            return jjStopAtPos(1, 69);
         else if ((active1 & 0x40L) != 0L)
            return jjStopAtPos(1, 70);
         else if ((active1 & 0x80L) != 0L)
            return jjStopAtPos(1, 71);
         else if ((active1 & 0x100L) != 0L)
            return jjStopAtPos(1, 72);
         break;
      case 62:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8000000000000400L, active2, 0L);
      case 67:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x7ff000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x10200L, active1, 0x2004000000000L, active2, 0x10L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800000000000L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x2001000L, active1, 0L, active2, 0x2L);
      case 102:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(1, 21, 36);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x84000400L, active1, 0x1800000000000000L, active2, 0x8L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L, active1, 0x400000000000L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x48000L, active1, 0x20000000000000L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x100020000000000L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L, active1, 0x240000000000000L, active2, 0x1L);
      case 111:
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x40984880L, active1, 0x8000000000000L, active2, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x30000100L, active1, 0x4300000000000L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x4L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x10040000000000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L, active1, 0x2000080000000000L, active2, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000L, active1, 0L, active2, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x80000000000000L, active2, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x4001000000000000L, active2, 0L);
      case 124:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStopAtPos(1, 52);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case 46:
         if ((active1 & 0x800L) != 0L)
            return jjStopAtPos(2, 75);
         break;
      case 61:
         if ((active1 & 0x200L) != 0L)
            return jjStopAtPos(2, 73);
         else if ((active1 & 0x400L) != 0L)
            return jjStopAtPos(2, 74);
         break;
      case 62:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x8000000000000000L, active2, 0L);
      case 95:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x7ff000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L, active1, 0x24040000000000L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x80000000000L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4000000000L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L, active1, 0L, active2, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L, active1, 0L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0xc8000000L, active1, 0x1000200000000000L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x1010000L, active1, 0x8000000000000L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x820800L, active1, 0x1400000000000L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4040080L, active1, 0x100000000000L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x2100020000000000L, active2, 0L);
      case 114:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(2, 19, 36);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x810000000000000L, active2, 0x8L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x8200L, active1, 0x800000000000L, active2, 0x5L);
      case 116:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x2100000L, active1, 0x40c2000000000000L, active2, 0x10L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x10004000L, active1, 0x200000000000000L, active2, 0L);
      case 119:
         if ((active2 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(2, 99, 36);
         break;
      case 121:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(2, 29, 36);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, active2);
      return 3;
   }
   switch(curChar)
   {
      case 61:
         if ((active1 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(3, 127);
         break;
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0xf4000L, active2, 0L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x2000L, active2, 0L);
      case 76:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x100000L, active2, 0L);
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x601000L, active2, 0L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x8000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x61100L, active1, 0x8400000000000L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L, active1, 0L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x1000000000000L, active2, 0x10L);
      case 100:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 36);
         break;
      case 101:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(3, 9, 36);
         else if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(3, 15, 36);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 28, 36);
         else if ((active1 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 99, 36);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x20c0000000000000L, active2, 0x4L);
      case 103:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 23, 36);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x12000000000000L, active2, 0L);
      case 107:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x4000000000L, active2, 0L);
      case 108:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 36);
         return jjMoveStringLiteralDfa4_0(active0, 0x80000080L, active1, 0x100080000000000L, active2, 0L);
      case 109:
         if ((active1 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 99, 36);
         break;
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x4000000000000L, active2, 0L);
      case 111:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 36);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x800020000000000L, active2, 0x8L);
      case 114:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 10, 36);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L, active1, 0L, active2, 0L);
      case 115:
         if ((active1 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 99, 36);
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L, active1, 0x20000000000000L, active2, 0L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000800L, active1, 0x940000000000L, active2, 0x1L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L, active1, 0L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x200000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, active2);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(2, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, active2);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x100000L, active2, 0L);
      case 69:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x8000L, active2, 0L);
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x2000L, active2, 0L);
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0xf4000L, active2, 0L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x601000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x204000000000L, active2, 0x1L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L, active1, 0x10000000000000L, active2, 0L);
      case 101:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(4, 16, 36);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 31, 36);
         return jjMoveStringLiteralDfa5_0(active0, 0x80L, active1, 0x100100000000000L, active2, 0L);
      case 104:
         if ((active2 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(4, 99, 36);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x1000000000000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L, active1, 0xc0000000000L, active2, 0L);
      case 107:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 8, 36);
         break;
      case 108:
         if ((active1 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x24000L, active1, 0L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x80000000000000L, active2, 0L);
      case 114:
         if ((active1 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 99, 36);
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L, active1, 0x40820000000000L, active2, 0x4L);
      case 115:
         if ((active1 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 99, 36);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x4000000000000L, active2, 0L);
      case 116:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(4, 18, 36);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(4, 26, 36);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x8000000000000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000L, active1, 0L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x2000000000000L, active2, 0L);
      case 119:
         if ((active2 & 0x8L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x800000000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, active2);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(3, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, active2);
      return 5;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x1000L, active2, 0L);
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x2000L, active2, 0L);
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x1f0000L, active2, 0L);
      case 79:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x600000L, active2, 0L);
      case 80:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x4000L, active2, 0L);
      case 86:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x8000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x80L, active1, 0x800000000000L, active2, 0L);
      case 99:
         if ((active1 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 99, 36);
         else if ((active1 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 99, 36);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x100000000000L, active2, 0L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x80000000000000L, active2, 0L);
      case 101:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 14, 36);
         else if ((active1 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 99, 36);
         break;
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x40000000000000L, active2, 0L);
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x4000000000L, active2, 0L);
      case 104:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(5, 27, 36);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0xc000000000000L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x21000L, active1, 0L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x100000000000000L, active2, 0L);
      case 110:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(5, 25, 36);
         return jjMoveStringLiteralDfa6_0(active0, 0x800L, active1, 0L, active2, 0x1L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x1000000000000L, active2, 0L);
      case 115:
         if ((active1 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 99, 36);
         break;
      case 116:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 99, 36);
         else if ((active2 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(5, 99, 36);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x10200000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, active2);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(4, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, active2);
      return 6;
   }
   switch(curChar)
   {
      case 70:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0xf0000L, active2, 0L);
      case 71:
         if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 84, 36);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x600000L, active2, 0L);
      case 73:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x8000L, active2, 0L);
      case 82:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x1000L, active2, 0L);
      case 84:
         if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(6, 77, 36);
         break;
      case 89:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x4000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x40000000000000L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x800000000000L, active2, 0x1L);
      case 101:
         if ((active1 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 99, 36);
         else if ((active1 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 99, 36);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x104000000000000L, active2, 0L);
      case 102:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x10000000000000L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x8000000000000L, active2, 0L);
      case 110:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(6, 7, 36);
         break;
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x1000000000000L, active2, 0L);
      case 115:
         if ((active1 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 99, 36);
         break;
      case 116:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(6, 12, 36);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x100000000000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x800L, active1, 0L, active2, 0L);
      case 121:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(6, 17, 36);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, active2);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(5, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, active2);
      return 7;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x1000L, active2, 0L);
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0xf0000L, active2, 0L);
      case 82:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x4000L, active2, 0L);
      case 83:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x8000L, active2, 0L);
      case 95:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x600000L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x40000000000000L, active2, 0L);
      case 101:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(7, 11, 36);
         else if ((active1 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 99, 36);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x100000000000L, active2, 0x1L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x105000000000000L, active2, 0L);
      case 112:
         if ((active1 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 99, 36);
         break;
      case 116:
         if ((active1 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 99, 36);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, active2);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(6, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, 0L, active1, active2);
      return 8;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa9_0(active1, 0x600000L, active2, 0L);
      case 71:
         return jjMoveStringLiteralDfa9_0(active1, 0xf0000L, active2, 0L);
      case 73:
         return jjMoveStringLiteralDfa9_0(active1, 0xc000L, active2, 0L);
      case 81:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(8, 76, 36);
         break;
      case 100:
         if ((active1 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 99, 36);
         break;
      case 101:
         if ((active1 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 99, 36);
         break;
      case 105:
         return jjMoveStringLiteralDfa9_0(active1, 0x1000000000000L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active1, 0L, active2, 0x1L);
      case 116:
         if ((active1 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 99, 36);
         return jjMoveStringLiteralDfa9_0(active1, 0x100000000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(7, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa9_0(long old1, long active1, long old2, long active2)
{
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(7, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, 0L, active1, active2);
      return 9;
   }
   switch(curChar)
   {
      case 67:
         if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(9, 85, 36);
         break;
      case 71:
         return jjMoveStringLiteralDfa10_0(active1, 0x4000L, active2, 0L);
      case 79:
         return jjMoveStringLiteralDfa10_0(active1, 0x8000L, active2, 0L);
      case 88:
         return jjMoveStringLiteralDfa10_0(active1, 0x400000L, active2, 0L);
      case 95:
         return jjMoveStringLiteralDfa10_0(active1, 0xf0000L, active2, 0L);
      case 102:
         if ((active2 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(9, 99, 36);
         break;
      case 115:
         if ((active1 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 99, 36);
         break;
      case 122:
         return jjMoveStringLiteralDfa10_0(active1, 0x1000000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(8, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa10_0(long old1, long active1, long old2, long active2)
{
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(8, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, 0L, active1, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa11_0(active1, 0x20000L);
      case 70:
         return jjMoveStringLiteralDfa11_0(active1, 0x40000L);
      case 72:
         return jjMoveStringLiteralDfa11_0(active1, 0x4000L);
      case 77:
         return jjMoveStringLiteralDfa11_0(active1, 0x80000L);
      case 78:
         if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(10, 79, 36);
         break;
      case 83:
         return jjMoveStringLiteralDfa11_0(active1, 0x10000L);
      case 88:
         if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(10, 86, 36);
         break;
      case 101:
         return jjMoveStringLiteralDfa11_0(active1, 0x1000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa11_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(9, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, 0L, active1, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa12_0(active1, 0x80000L);
      case 73:
         return jjMoveStringLiteralDfa12_0(active1, 0x40000L);
      case 82:
         return jjMoveStringLiteralDfa12_0(active1, 0x10000L);
      case 84:
         if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(11, 78, 36);
         break;
      case 85:
         return jjMoveStringLiteralDfa12_0(active1, 0x20000L);
      case 100:
         if ((active1 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 99, 36);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa12_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(10, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, 0L, active1, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa13_0(active1, 0x90000L);
      case 76:
         return jjMoveStringLiteralDfa13_0(active1, 0x40000L);
      case 88:
         return jjMoveStringLiteralDfa13_0(active1, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(11, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa13_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(11, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, 0L, active1, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa14_0(active1, 0x10000L);
      case 69:
         return jjMoveStringLiteralDfa14_0(active1, 0x40000L);
      case 82:
         return jjMoveStringLiteralDfa14_0(active1, 0x80000L);
      case 95:
         return jjMoveStringLiteralDfa14_0(active1, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(12, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa14_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(12, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, 0L, active1, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa15_0(active1, 0x20000L);
      case 73:
         return jjMoveStringLiteralDfa15_0(active1, 0x10000L);
      case 79:
         return jjMoveStringLiteralDfa15_0(active1, 0x80000L);
      case 83:
         if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(14, 82, 36);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa15_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(13, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, 0L, active1, 0L);
      return 15;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa16_0(active1, 0x20000L);
      case 82:
         if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(15, 80, 36);
         break;
      case 95:
         return jjMoveStringLiteralDfa16_0(active1, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(14, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa16_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(14, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, 0L, active1, 0L);
      return 16;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa17_0(active1, 0x80000L);
      case 82:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(16, 81, 36);
         break;
      default :
         break;
   }
   return jjStartNfa_0(15, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa17_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(15, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, 0L, active1, 0L);
      return 17;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa18_0(active1, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(16, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa18_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(16, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, 0L, active1, 0L);
      return 18;
   }
   switch(curChar)
   {
      case 82:
         return jjMoveStringLiteralDfa19_0(active1, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(17, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa19_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(17, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, 0L, active1, 0L);
      return 19;
   }
   switch(curChar)
   {
      case 83:
         if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(19, 83, 36);
         break;
      default :
         break;
   }
   return jjStartNfa_0(18, 0L, active1, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 69;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 6);
                  else if (curChar == 36)
                  {
                     if (kind > 99)
                        kind = 99;
                     jjCheckNAdd(36);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(7, 9);
                  else if (curChar == 39)
                     jjAddStates(10, 11);
                  else if (curChar == 46)
                     jjCheckNAdd(9);
                  else if (curChar == 35)
                  {
                     if (kind > 6)
                        kind = 6;
                     jjCheckNAddStates(12, 14);
                  }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 87)
                        kind = 87;
                     jjCheckNAddTwoStates(6, 7);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 87)
                        kind = 87;
                     jjCheckNAddStates(15, 19);
                  }
                  break;
               case 69:
               case 33:
                  jjCheckNAddTwoStates(33, 34);
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAddStates(12, 14);
                  break;
               case 2:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 3:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 4:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddTwoStates(6, 7);
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddTwoStates(6, 7);
                  break;
               case 8:
                  if (curChar == 46)
                     jjCheckNAdd(9);
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAddStates(20, 22);
                  break;
               case 11:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(12);
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAddTwoStates(12, 13);
                  break;
               case 14:
                  if (curChar == 39)
                     jjAddStates(10, 11);
                  break;
               case 15:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 16:
                  if (curChar == 39 && kind > 96)
                     kind = 96;
                  break;
               case 18:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 19:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(20, 16);
                  break;
               case 20:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 21:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 22:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(20);
                  break;
               case 23:
                  if (curChar == 34)
                     jjCheckNAddStates(7, 9);
                  break;
               case 24:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 26:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 27:
                  if (curChar == 34 && kind > 97)
                     kind = 97;
                  break;
               case 28:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(23, 26);
                  break;
               case 29:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 30:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(29);
                  break;
               case 35:
                  if (curChar != 36)
                     break;
                  if (kind > 99)
                     kind = 99;
                  jjCheckNAdd(36);
                  break;
               case 36:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 99)
                     kind = 99;
                  jjCheckNAdd(36);
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 6);
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(27, 29);
                  break;
               case 40:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(41);
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(41, 13);
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(42, 43);
                  break;
               case 44:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(45);
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAddTwoStates(45, 13);
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(46, 47);
                  break;
               case 47:
                  if (curChar != 46)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAddStates(30, 32);
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAddStates(30, 32);
                  break;
               case 50:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(51);
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAddTwoStates(51, 13);
                  break;
               case 52:
                  if (curChar != 48)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddStates(15, 19);
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddTwoStates(54, 7);
                  break;
               case 55:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddTwoStates(55, 7);
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(33, 34);
                  break;
               case 58:
                  if (curChar == 46)
                     jjCheckNAdd(59);
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(59, 60);
                  break;
               case 61:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(62);
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAddTwoStates(62, 13);
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(35, 37);
                  break;
               case 65:
                  if (curChar == 46)
                     jjCheckNAdd(66);
                  break;
               case 67:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(68);
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAddTwoStates(68, 13);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 99)
                        kind = 99;
                     jjCheckNAdd(36);
                  }
                  else if (curChar == 91)
                     jjCheckNAddTwoStates(33, 34);
                  break;
               case 69:
                  if ((0xffffffffdfffffffL & l) != 0L)
                     jjCheckNAddTwoStates(33, 34);
                  else if (curChar == 93)
                  {
                     if (kind > 98)
                        kind = 98;
                  }
                  break;
               case 1:
                  if (kind > 6)
                     kind = 6;
                  jjAddStates(12, 14);
                  break;
               case 7:
                  if ((0x100000001000L & l) != 0L && kind > 87)
                     kind = 87;
                  break;
               case 10:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(38, 39);
                  break;
               case 13:
                  if ((0x5000000050L & l) != 0L && kind > 91)
                     kind = 91;
                  break;
               case 15:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 17:
                  if (curChar == 92)
                     jjAddStates(40, 42);
                  break;
               case 18:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 24:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 25:
                  if (curChar == 92)
                     jjAddStates(43, 45);
                  break;
               case 26:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 32:
                  if (curChar == 91)
                     jjCheckNAddTwoStates(33, 34);
                  break;
               case 33:
                  if ((0xffffffffdfffffffL & l) != 0L)
                     jjCheckNAddTwoStates(33, 34);
                  break;
               case 34:
                  if (curChar == 93 && kind > 98)
                     kind = 98;
                  break;
               case 35:
               case 36:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 99)
                     kind = 99;
                  jjCheckNAdd(36);
                  break;
               case 39:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(46, 47);
                  break;
               case 43:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(48, 49);
                  break;
               case 49:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(50, 51);
                  break;
               case 53:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(54);
                  break;
               case 54:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAddTwoStates(54, 7);
                  break;
               case 56:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAddTwoStates(57, 58);
                  break;
               case 57:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(57, 58);
                  break;
               case 59:
                  if ((0x7e0000007eL & l) != 0L)
                     jjAddStates(52, 53);
                  break;
               case 60:
                  if ((0x1000000010000L & l) != 0L)
                     jjAddStates(54, 55);
                  break;
               case 63:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(64);
                  break;
               case 64:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(35, 37);
                  break;
               case 66:
                  if ((0x1000000010000L & l) != 0L)
                     jjAddStates(56, 57);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 69:
               case 33:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(33, 34);
                  break;
               case 1:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjAddStates(12, 14);
                  break;
               case 15:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 24:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(7, 9);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 69 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   38, 39, 13, 42, 43, 46, 47, 24, 25, 27, 15, 17, 1, 2, 4, 53, 
   55, 7, 56, 63, 9, 10, 13, 24, 25, 29, 27, 38, 39, 13, 48, 49, 
   13, 57, 58, 64, 65, 66, 11, 12, 18, 19, 21, 26, 28, 30, 40, 41, 
   44, 45, 50, 51, 59, 60, 61, 62, 67, 68, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\142\157\157\154\145\141\156", 
"\142\162\145\141\153", "\143\141\163\145", "\143\150\141\162", "\143\157\156\164\151\156\165\145", 
"\144\145\146\141\165\154\164", "\144\157", "\144\157\165\142\154\145", "\145\154\163\145", 
"\146\141\154\163\145", "\146\151\156\141\154\154\171", "\146\154\157\141\164", "\146\157\162", 
"\147\157\164\157", "\151\146", "\151\156\164", "\154\157\156\147", "\156\165\154\154", 
"\162\145\164\165\162\156", "\163\150\157\162\164", "\163\167\151\164\143\150", "\164\162\165\145", 
"\164\162\171", "\166\157\151\144", "\167\150\151\154\145", "\50", "\51", "\173", "\175", 
"\133", "\135", "\73", "\54", "\56", "\100", "\75", "\74", "\41", "\176", "\77", 
"\72", "\75\75", "\74\75", "\76\75", "\41\75", "\174\174", "\46\46", "\53\53", 
"\55\55", "\53", "\55", "\52", "\57", "\46", "\174", "\136", "\45", "\74\74", "\53\75", 
"\55\75", "\52\75", "\57\75", "\46\75", "\174\75", "\136\75", "\45\75", "\74\74\75", 
"\76\76\75", "\56\56\56", "\101\103\137\120\122\105\122\105\121", 
"\101\103\137\111\116\111\124", "\101\103\137\103\117\120\131\122\111\107\110\124", 
"\101\103\137\122\105\126\111\123\111\117\116", "\101\103\137\103\117\116\106\111\107\137\123\122\103\104\111\122", 
"\101\103\137\103\117\116\106\111\107\137\101\125\130\137\104\111\122", "\101\103\137\103\117\116\106\111\107\137\106\111\114\105\123", 
"\101\103\137\103\117\116\106\111\107\137\115\101\103\122\117\137\104\111\122\123", "\101\103\137\114\101\116\107", "\101\103\137\120\122\117\107\137\103\103", 
"\101\103\137\120\122\117\107\137\103\130\130", null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, "\160\141\143\153\141\147\145", "\32", null, "\151\155\160\157\162\164", 
"\163\164\141\164\151\143", "\160\165\142\154\151\143", "\160\162\157\164\145\143\164\145\144", 
"\160\162\151\166\141\164\145", "\146\151\156\141\154", "\141\142\163\164\162\141\143\164", 
"\163\171\156\143\150\162\157\156\151\172\145\144", "\156\141\164\151\166\145", "\164\162\141\156\163\151\145\156\164", 
"\166\157\154\141\164\151\154\145", "\163\164\162\151\143\164\146\160", "\143\154\141\163\163", 
"\151\156\164\145\162\146\141\143\145", "\145\170\164\145\156\144\163", "\151\155\160\154\145\155\145\156\164\163", 
"\145\156\165\155", "\76", "\164\150\162\157\167\163", "\164\150\151\163", "\163\165\160\145\162", 
"\142\171\164\145", "\76\76\76\75", "\151\156\163\164\141\156\143\145\157\146", "\156\145\167", 
"\141\163\163\145\162\164", "\164\150\162\157\167", "\143\141\164\143\150", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffffff81L, 0xffffffcf08ffffffL, 0x1fL, 
};
static final long[] jjtoSkip = {
   0x7eL, 0x0L, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x40L, 0x0L, 0x0L, 
};
protected JavaCharStream input_stream;
private final int[] jjrounds = new int[69];
private final int[] jjstateSet = new int[138];
protected char curChar;
/** Constructor. */
public AutoconfParserTokenManager(JavaCharStream stream){
   if (JavaCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public AutoconfParserTokenManager(JavaCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(JavaCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 69; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(JavaCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = MyToken.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 104)
   {
      jjmatchedKind = 104;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
