/* Generated By:JavaCC: Do not edit this line. AutoconfParserConstants.java */
package org.netbeans.gnu.autotools.autoconf.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AutoconfParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int BOOLEAN = 7;
  /** RegularExpression Id. */
  int BREAK = 8;
  /** RegularExpression Id. */
  int CASE = 9;
  /** RegularExpression Id. */
  int CHAR = 10;
  /** RegularExpression Id. */
  int CONTINUE = 11;
  /** RegularExpression Id. */
  int _DEFAULT = 12;
  /** RegularExpression Id. */
  int DO = 13;
  /** RegularExpression Id. */
  int DOUBLE = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int FINALLY = 17;
  /** RegularExpression Id. */
  int FLOAT = 18;
  /** RegularExpression Id. */
  int FOR = 19;
  /** RegularExpression Id. */
  int GOTO = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int INT = 22;
  /** RegularExpression Id. */
  int LONG = 23;
  /** RegularExpression Id. */
  int NULL = 24;
  /** RegularExpression Id. */
  int RETURN = 25;
  /** RegularExpression Id. */
  int SHORT = 26;
  /** RegularExpression Id. */
  int SWITCH = 27;
  /** RegularExpression Id. */
  int TRUE = 28;
  /** RegularExpression Id. */
  int TRY = 29;
  /** RegularExpression Id. */
  int VOID = 30;
  /** RegularExpression Id. */
  int WHILE = 31;
  /** RegularExpression Id. */
  int LPAREN = 32;
  /** RegularExpression Id. */
  int RPAREN = 33;
  /** RegularExpression Id. */
  int LBRACE = 34;
  /** RegularExpression Id. */
  int RBRACE = 35;
  /** RegularExpression Id. */
  int LBRACKET = 36;
  /** RegularExpression Id. */
  int RBRACKET = 37;
  /** RegularExpression Id. */
  int SEMICOLON = 38;
  /** RegularExpression Id. */
  int COMMA = 39;
  /** RegularExpression Id. */
  int DOT = 40;
  /** RegularExpression Id. */
  int AT = 41;
  /** RegularExpression Id. */
  int ASSIGN = 42;
  /** RegularExpression Id. */
  int LT = 43;
  /** RegularExpression Id. */
  int BANG = 44;
  /** RegularExpression Id. */
  int TILDE = 45;
  /** RegularExpression Id. */
  int HOOK = 46;
  /** RegularExpression Id. */
  int COLON = 47;
  /** RegularExpression Id. */
  int EQ = 48;
  /** RegularExpression Id. */
  int LE = 49;
  /** RegularExpression Id. */
  int GE = 50;
  /** RegularExpression Id. */
  int NE = 51;
  /** RegularExpression Id. */
  int SC_OR = 52;
  /** RegularExpression Id. */
  int SC_AND = 53;
  /** RegularExpression Id. */
  int INCR = 54;
  /** RegularExpression Id. */
  int DECR = 55;
  /** RegularExpression Id. */
  int PLUS = 56;
  /** RegularExpression Id. */
  int MINUS = 57;
  /** RegularExpression Id. */
  int STAR = 58;
  /** RegularExpression Id. */
  int SLASH = 59;
  /** RegularExpression Id. */
  int BIT_AND = 60;
  /** RegularExpression Id. */
  int BIT_OR = 61;
  /** RegularExpression Id. */
  int XOR = 62;
  /** RegularExpression Id. */
  int REM = 63;
  /** RegularExpression Id. */
  int LSHIFT = 64;
  /** RegularExpression Id. */
  int PLUSASSIGN = 65;
  /** RegularExpression Id. */
  int MINUSASSIGN = 66;
  /** RegularExpression Id. */
  int STARASSIGN = 67;
  /** RegularExpression Id. */
  int SLASHASSIGN = 68;
  /** RegularExpression Id. */
  int ANDASSIGN = 69;
  /** RegularExpression Id. */
  int ORASSIGN = 70;
  /** RegularExpression Id. */
  int XORASSIGN = 71;
  /** RegularExpression Id. */
  int REMASSIGN = 72;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 73;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 74;
  /** RegularExpression Id. */
  int ELLIPSIS = 75;
  /** RegularExpression Id. */
  int AC_PREREQ = 76;
  /** RegularExpression Id. */
  int AC_INIT = 77;
  /** RegularExpression Id. */
  int AC_COPYRIGHT = 78;
  /** RegularExpression Id. */
  int AC_REVISION = 79;
  /** RegularExpression Id. */
  int AC_CONFIG_SRCDIR = 80;
  /** RegularExpression Id. */
  int AC_CONFIG_AUX_DIR = 81;
  /** RegularExpression Id. */
  int AC_CONFIG_FILES = 82;
  /** RegularExpression Id. */
  int AC_CONFIG_MACRO_DIRS = 83;
  /** RegularExpression Id. */
  int AC_LANG = 84;
  /** RegularExpression Id. */
  int AC_PROG_CC = 85;
  /** RegularExpression Id. */
  int AC_PROG_CXX = 86;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 87;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 88;
  /** RegularExpression Id. */
  int HEX_LITERAL = 89;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 90;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 91;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 92;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 93;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 94;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 95;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 96;
  /** RegularExpression Id. */
  int STRING_LITERAL = 97;
  /** RegularExpression Id. */
  int M4_LITERAL = 98;
  /** RegularExpression Id. */
  int IDENTIFIER = 99;
  /** RegularExpression Id. */
  int LETTER = 100;
  /** RegularExpression Id. */
  int PART_LETTER = 101;
  /** RegularExpression Id. */
  int STUFF_TO_IGNORE = 104;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"boolean\"",
    "\"break\"",
    "\"case\"",
    "\"char\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"false\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"int\"",
    "\"long\"",
    "\"null\"",
    "\"return\"",
    "\"short\"",
    "\"switch\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"...\"",
    "\"AC_PREREQ\"",
    "\"AC_INIT\"",
    "\"AC_COPYRIGHT\"",
    "\"AC_REVISION\"",
    "\"AC_CONFIG_SRCDIR\"",
    "\"AC_CONFIG_AUX_DIR\"",
    "\"AC_CONFIG_FILES\"",
    "\"AC_CONFIG_MACRO_DIRS\"",
    "\"AC_LANG\"",
    "\"AC_PROG_CC\"",
    "\"AC_PROG_CXX\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<M4_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"package\"",
    "\"\\u001a\"",
    "<STUFF_TO_IGNORE>",
    "\"import\"",
    "\"static\"",
    "\"public\"",
    "\"protected\"",
    "\"private\"",
    "\"final\"",
    "\"abstract\"",
    "\"synchronized\"",
    "\"native\"",
    "\"transient\"",
    "\"volatile\"",
    "\"strictfp\"",
    "\"class\"",
    "\"interface\"",
    "\"extends\"",
    "\"implements\"",
    "\"enum\"",
    "\">\"",
    "\"throws\"",
    "\"this\"",
    "\"super\"",
    "\"byte\"",
    "\">>>=\"",
    "\"instanceof\"",
    "\"new\"",
    "\"assert\"",
    "\"throw\"",
    "\"catch\"",
  };

}
