/* 
 * Copyright (C) 2014, Enrico M. Crisostomo
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.netbeans.gnu.autotools.autoconf.lexer;

import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.netbeans.spi.lexer.LanguageHierarchy;
import org.netbeans.spi.lexer.Lexer;
import org.netbeans.spi.lexer.LexerRestartInfo;

/**
 *
 * @author Enrico M. Crisostomo
 */
public class ACLanguageHierarchy extends LanguageHierarchy<ACTokenId> {

    private static List<ACTokenId> tokens;
    private static Map<Integer, ACTokenId> idToToken;

    private static void init() {
        int regExCounter = 0;
        tokens = Arrays.asList(new ACTokenId[]{
            // whitespace and comments
            new ACTokenId("EOF", "whitespace", regExCounter++),
            new ACTokenId("WHITESPACE", "whitespace", regExCounter++),
            new ACTokenId("SINGLE_LINE_COMMENT", "comment", regExCounter++),
            // Operators
            new ACTokenId("LBRACKET", "operator", regExCounter++),
            new ACTokenId("MLBRACKET", "operator", regExCounter++),
            new ACTokenId("MRBRACKET", "operator", regExCounter++),
            new ACTokenId("RBRACKET", "operator", regExCounter++),
            // Reserved words
            new ACTokenId("BOOLEAN", "keyword", regExCounter++),
            new ACTokenId("BREAK", "keyword", regExCounter++),
            new ACTokenId("CASE", "keyword", regExCounter++),
            new ACTokenId("CHAR", "keyword", regExCounter++),
            new ACTokenId("CONTINUE", "keyword", regExCounter++),
            new ACTokenId("_DEFAULT", "keyword", regExCounter++),
            new ACTokenId("DO", "keyword", regExCounter++),
            new ACTokenId("DONE", "keyword", regExCounter++),
            new ACTokenId("DOUBLE", "keyword", regExCounter++),
            new ACTokenId("ELSE", "keyword", regExCounter++),
            new ACTokenId("FALSE", "keyword", regExCounter++),
            new ACTokenId("FINALLY", "keyword", regExCounter++),
            new ACTokenId("FLOAT", "keyword", regExCounter++),
            new ACTokenId("FOR", "keyword", regExCounter++),
            new ACTokenId("GOTO", "keyword", regExCounter++),
            new ACTokenId("IF", "keyword", regExCounter++),
            new ACTokenId("FI", "keyword", regExCounter++),
            new ACTokenId("INT", "keyword", regExCounter++),
            new ACTokenId("LONG", "keyword", regExCounter++),
            new ACTokenId("NULL", "keyword", regExCounter++),
            new ACTokenId("RETURN", "keyword", regExCounter++),
            new ACTokenId("SHORT", "keyword", regExCounter++),
            new ACTokenId("SWITCH", "keyword", regExCounter++),
            new ACTokenId("THEN", "keyword", regExCounter++),
            new ACTokenId("TRUE", "keyword", regExCounter++),
            new ACTokenId("TRY", "keyword", regExCounter++),
            new ACTokenId("VOID", "keyword", regExCounter++),
            new ACTokenId("WHILE", "keyword", regExCounter++),
            // Separators
            new ACTokenId("LPAREN", "operator", regExCounter++),
            new ACTokenId("RPAREN", "operator", regExCounter++),
            new ACTokenId("LBRACE", "operator", regExCounter++),
            new ACTokenId("RBRACE", "operator", regExCounter++),
            new ACTokenId("SEMICOLON", "operator", regExCounter++),
            new ACTokenId("COMMA", "operator", regExCounter++),
            new ACTokenId("DOT", "operator", regExCounter++),
            // Operators  
            new ACTokenId("ASSIGN", "operator", regExCounter++),
            new ACTokenId("LT", "operator", regExCounter++),
            new ACTokenId("BANG", "operator", regExCounter++),
            new ACTokenId("TILDE", "operator", regExCounter++),
            new ACTokenId("HOOK", "operator", regExCounter++),
            new ACTokenId("COLON", "operator", regExCounter++),
            new ACTokenId("EQ", "operator", regExCounter++),
            new ACTokenId("LE", "operator", regExCounter++),
            new ACTokenId("GE", "operator", regExCounter++),
            new ACTokenId("NE", "operator", regExCounter++),
            new ACTokenId("SC_OR", "operator", regExCounter++),
            new ACTokenId("SC_AND", "operator", regExCounter++),
            new ACTokenId("INCR", "operator", regExCounter++),
            new ACTokenId("DECR", "operator", regExCounter++),
            new ACTokenId("PLUS", "operator", regExCounter++),
            new ACTokenId("MINUS", "operator", regExCounter++),
            new ACTokenId("STAR", "operator", regExCounter++),
            new ACTokenId("SLASH", "operator", regExCounter++),
            new ACTokenId("BIT_AND", "operator", regExCounter++),
            new ACTokenId("BIT_OR", "operator", regExCounter++),
            new ACTokenId("XOR", "operator", regExCounter++),
            new ACTokenId("REM", "operator", regExCounter++),
            new ACTokenId("LSHIFT", "operator", regExCounter++),
            new ACTokenId("PLUSASSIGN", "operator", regExCounter++),
            new ACTokenId("MINUSASSIGN", "operator", regExCounter++),
            new ACTokenId("STARASSIGN", "operator", regExCounter++),
            new ACTokenId("SLASHASSIGN", "operator", regExCounter++),
            new ACTokenId("ANDASSIGN", "operator", regExCounter++),
            new ACTokenId("ORASSIGN", "operator", regExCounter++),
            new ACTokenId("XORASSIGN", "operator", regExCounter++),
            new ACTokenId("REMASSIGN", "operator", regExCounter++),
            new ACTokenId("LSHIFTASSIGN", "operator", regExCounter++),
            new ACTokenId("RSIGNEDSHIFTASSIGN", "operator", regExCounter++),
            new ACTokenId("ELLIPSIS", "operator", regExCounter++),
            // Quadrigraphs
            new ACTokenId("LBRACKET_QG", "operator", regExCounter++),
            new ACTokenId("RBRACKET_QG", "operator", regExCounter++),
            new ACTokenId("DOLLAR_QG", "operator", regExCounter++),
            new ACTokenId("BANG_QG", "operator", regExCounter++),
            new ACTokenId("LBRACE_QG", "operator", regExCounter++),
            new ACTokenId("RBRACE_QG", "operator", regExCounter++),
            new ACTokenId("EMPTY_QG", "operator", regExCounter++),
            //  Literals
            new ACTokenId("INTEGER_LITERAL", "number", regExCounter++),
            new ACTokenId("DECIMAL_LITERAL", "number", regExCounter++),
            new ACTokenId("HEX_LITERAL", "number", regExCounter++),
            new ACTokenId("OCTAL_LITERAL", "number", regExCounter++),
            new ACTokenId("FLOATING_POINT_LITERAL", "number", regExCounter++),
            new ACTokenId("DECIMAL_FLOATING_POINT_LITERAL", "number", regExCounter++),
            new ACTokenId("DECIMAL_EXPONENT", "number", regExCounter++),
            new ACTokenId("HEXADECIMAL_FLOATING_POINT_LITERAL", "number", regExCounter++),
            new ACTokenId("HEXADECIMAL_EXPONENT", "number", regExCounter++),
            new ACTokenId("CHARACTER_LITERAL", "character", regExCounter++),
            new ACTokenId("STRING_LITERAL", "string", regExCounter++),
            // Autoconf macros
            new ACTokenId("AC_ARG_VAR", "autoconf", regExCounter++),
            new ACTokenId("AC_ARG_ENABLE", "autoconf", regExCounter++),
            new ACTokenId("AC_ARG_PROGRAM", "autoconf", regExCounter++),
            new ACTokenId("AC_ARG_WITH", "autoconf", regExCounter++),
            new ACTokenId("AC_AUTOCONF_VERSION", "autoconf", regExCounter++),
            new ACTokenId("AC_BEFORE", "autoconf", regExCounter++),
            new ACTokenId("AC_C_BACKSLASH_A", "autoconf", regExCounter++),
            new ACTokenId("AC_C_BIGENDIAN", "autoconf", regExCounter++),
            new ACTokenId("AC_C_CHAR_UNSIGNED", "autoconf", regExCounter++),
            new ACTokenId("AC_C_CONST", "autoconf", regExCounter++),
            new ACTokenId("AC_C_FLEXIBLE_ARRAY_MEMBER", "autoconf", regExCounter++),
            new ACTokenId("AC_C_INLINE", "autoconf", regExCounter++),
            new ACTokenId("AC_C_PROTOTYPES", "autoconf", regExCounter++),
            new ACTokenId("AC_C_RESTRICT", "autoconf", regExCounter++),
            new ACTokenId("AC_C_STRINGIZE", "autoconf", regExCounter++),
            new ACTokenId("AC_C_TYPEOF", "autoconf", regExCounter++),
            new ACTokenId("AC_C_VARARRAYS", "autoconf", regExCounter++),
            new ACTokenId("AC_C_VOLATILE", "autoconf", regExCounter++),
            new ACTokenId("AC_CACHE_CHECK", "autoconf", regExCounter++),
            new ACTokenId("AC_CACHE_LOAD", "autoconf", regExCounter++),
            new ACTokenId("AC_CACHE_SAVE", "autoconf", regExCounter++),
            new ACTokenId("AC_CACHE_VAL", "autoconf", regExCounter++),
            new ACTokenId("AC_CANONICAL_BUILD", "autoconf", regExCounter++),
            new ACTokenId("AC_CANONICAL_HOST", "autoconf", regExCounter++),
            new ACTokenId("AC_CANONICAL_TARGET", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_ALIGNOF", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_DECL", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_DECLS", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_DECLS_ONCE", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_FILE", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_FILES", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_FUNC", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_FUNCS", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_FUNCS_ONCE", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_LIB", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_HEADER", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_HEADER_STDBOOL", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_HEADERS", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_HEADERS_ONCE", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_MEMBER", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_MEMBERS", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_PROG", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_PROGS", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_SIZEOF", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_TARGET_TOOL", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_TARGET_TOOLS", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_TYPE", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_TYPES", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_TOOL", "autoconf", regExCounter++),
            new ACTokenId("AC_CHECK_TOOLS", "autoconf", regExCounter++),
            new ACTokenId("AC_COMPILE_IFELSE", "autoconf", regExCounter++),
            new ACTokenId("AC_COMPUTE_INT", "autoconf", regExCounter++),
            new ACTokenId("AC_CONFIG_AUX_DIR", "autoconf", regExCounter++),
            new ACTokenId("AC_CONFIG_COMMANDS", "autoconf", regExCounter++),
            new ACTokenId("AC_CONFIG_COMMANDS_PRE", "autoconf", regExCounter++),
            new ACTokenId("AC_CONFIG_COMMANDS_POST", "autoconf", regExCounter++),
            new ACTokenId("AC_CONFIG_FILES", "autoconf", regExCounter++),
            new ACTokenId("AC_CONFIG_HEADERS", "autoconf", regExCounter++),
            new ACTokenId("AC_CONFIG_LIBOBJ_DIR", "autoconf", regExCounter++),
            new ACTokenId("AC_CONFIG_LINKS", "autoconf", regExCounter++),
            new ACTokenId("AC_CONFIG_MACRO_DIR", "autoconf", regExCounter++),
            new ACTokenId("AC_CONFIG_MACRO_DIRS", "autoconf", regExCounter++),
            new ACTokenId("AC_CONFIG_SRCDIR", "autoconf", regExCounter++),
            new ACTokenId("AC_CONFIG_SUBDIRS", "autoconf", regExCounter++),
            new ACTokenId("AC_COPYRIGHT", "autoconf", regExCounter++),
            new ACTokenId("AC_DEFINE", "autoconf", regExCounter++),
            new ACTokenId("AC_DEFINE_UNQUOTED", "autoconf", regExCounter++),
            new ACTokenId("AC_DEFUN", "autoconf", regExCounter++),
            new ACTokenId("AC_DEFUN_ONCE", "autoconf", regExCounter++),
            new ACTokenId("AC_DIAGNOSE", "autoconf", regExCounter++),
            new ACTokenId("AC_DISABLE_OPTION_CHECKING", "autoconf", regExCounter++),
            new ACTokenId("AC_EGREP_CPP", "autoconf", regExCounter++),
            new ACTokenId("AC_EGREP_HEADER", "autoconf", regExCounter++),
            new ACTokenId("AC_ERLANG_CHECK_LIB", "autoconf", regExCounter++),
            new ACTokenId("AC_ERLANG_NEED_ERL", "autoconf", regExCounter++),
            new ACTokenId("AC_ERLANG_NEED_ERLC", "autoconf", regExCounter++),
            new ACTokenId("AC_ERLANG_PATH_ERL", "autoconf", regExCounter++),
            new ACTokenId("AC_ERLANG_PATH_ERLC", "autoconf", regExCounter++),
            new ACTokenId("AC_ERLANG_SUBST_ERTS_VER", "autoconf", regExCounter++),
            new ACTokenId("AC_ERLANG_SUBST_INSTALL_LIB_DIR", "autoconf", regExCounter++),
            new ACTokenId("AC_ERLANG_SUBST_INSTALL_LIB_SUBDIR", "autoconf", regExCounter++),
            new ACTokenId("AC_ERLANG_SUBST_LIB_DIR", "autoconf", regExCounter++),
            new ACTokenId("AC_ERLANG_SUBST_ROOT_DIR", "autoconf", regExCounter++),
            new ACTokenId("AC_F77_DUMMY_MAIN", "autoconf", regExCounter++),
            new ACTokenId("AC_F77_FUNC", "autoconf", regExCounter++),
            new ACTokenId("AC_F77_IMPLICIT_NONE", "autoconf", regExCounter++),
            new ACTokenId("AC_F77_LIBRARY_LDFLAGS", "autoconf", regExCounter++),
            new ACTokenId("AC_F77_MAIN", "autoconf", regExCounter++),
            new ACTokenId("AC_F77_WRAPPERS", "autoconf", regExCounter++),
            new ACTokenId("AC_FATAL", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_CHECK_BOUNDS", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_DUMMY_MAIN", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_FIXEDFORM", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_FREEFORM", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_FUNC", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_IMPLICIT_NONE", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_LIBRARY_LDFLAGS", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_LINE_LENGTH", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_MAIN", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_MODULE_EXTENSION", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_MODULE_FLAG", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_MODULE_OUTPUT_FLAG", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_PP_DEFINE", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_PP_SRCEXT", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_SRCEXT", "autoconf", regExCounter++),
            new ACTokenId("AC_FC_WRAPPERS", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_ALLOCA", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_CHOWN", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_CLOSEDIR_VOID", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_ERROR_AT_LINE", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_FNMATCH", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_FNMATCH_GNU", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_FORK", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_FSEEKO", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_GETGROUPS", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_GETLOADAVG", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_GETMNTENT", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_GETPGRP", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_LSTAT_FOLLOWS_SLASHED_SYMLINK", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_MALLOC", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_MBRTOWC", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_MEMCMP", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_MKTIME", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_MMAP", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_OBSTACK", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_REALLOC", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_SELECT_ARGTYPES", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_SETPGRP", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_STAT", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_LSTAT", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_STRCOLL", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_STRERROR_R", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_STRFTIME", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_STRTOD", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_STRTOLD", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_STRNLEN", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_UTIME_NULL", "autoconf", regExCounter++),
            new ACTokenId("AC_FUNC_VPRINTF", "autoconf", regExCounter++),
            new ACTokenId("AC_HEADER_ASSERT", "autoconf", regExCounter++),
            new ACTokenId("AC_HEADER_DIRENT", "autoconf", regExCounter++),
            new ACTokenId("AC_HEADER_MAJOR", "autoconf", regExCounter++),
            new ACTokenId("AC_HEADER_RESOLV", "autoconf", regExCounter++),
            new ACTokenId("AC_HEADER_STAT", "autoconf", regExCounter++),
            new ACTokenId("AC_HEADER_STDBOOL", "autoconf", regExCounter++),
            new ACTokenId("AC_HEADER_STDC", "autoconf", regExCounter++),
            new ACTokenId("AC_HEADER_SYS_WAIT", "autoconf", regExCounter++),
            new ACTokenId("AC_HEADER_TIME", "autoconf", regExCounter++),
            new ACTokenId("AC_HEADER_TIOCGWINSZ", "autoconf", regExCounter++),
            new ACTokenId("AC_INCLUDES_DEFAULT", "autoconf", regExCounter++),
            new ACTokenId("AC_INIT", "autoconf", regExCounter++),
            new ACTokenId("AC_LANG", "autoconf", regExCounter++),
            new ACTokenId("AC_LANG_ASSERT", "autoconf", regExCounter++),
            new ACTokenId("AC_LANG_CALL", "autoconf", regExCounter++),
            new ACTokenId("AC_LANG_CONFTEST", "autoconf", regExCounter++),
            new ACTokenId("AC_LANG_DEFINES_PROVIDED", "autoconf", regExCounter++),
            new ACTokenId("AC_LANG_FUNC_LINK_TRY", "autoconf", regExCounter++),
            new ACTokenId("AC_LANG_POP", "autoconf", regExCounter++),
            new ACTokenId("AC_LANG_PROGRAM", "autoconf", regExCounter++),
            new ACTokenId("AC_LANG_PUSH", "autoconf", regExCounter++),
            new ACTokenId("AC_LANG_SOURCE", "autoconf", regExCounter++),
            new ACTokenId("AC_LANG_WERROR", "autoconf", regExCounter++),
            new ACTokenId("AC_LIBOBJ", "autoconf", regExCounter++),
            new ACTokenId("AC_LIBSOURCE", "autoconf", regExCounter++),
            new ACTokenId("AC_LIBSOURCES", "autoconf", regExCounter++),
            new ACTokenId("AC_LINK_IFELSE", "autoconf", regExCounter++),
            new ACTokenId("AC_MSG_CHECKING", "autoconf", regExCounter++),
            new ACTokenId("AC_MSG_ERROR", "autoconf", regExCounter++),
            new ACTokenId("AC_MSG_FAILURE", "autoconf", regExCounter++),
            new ACTokenId("AC_MSG_NOTICE", "autoconf", regExCounter++),
            new ACTokenId("AC_MSG_RESULT", "autoconf", regExCounter++),
            new ACTokenId("AC_MSG_WARN", "autoconf", regExCounter++),
            new ACTokenId("AC_OPENMP", "autoconf", regExCounter++),
            new ACTokenId("AC_OUTPUT", "autoconf", regExCounter++),
            new ACTokenId("AC_PACKAGE_BUGREPORT", "autoconf", regExCounter++),
            new ACTokenId("AC_PACKAGE_NAME", "autoconf", regExCounter++),
            new ACTokenId("AC_PACKAGE_STRING", "autoconf", regExCounter++),
            new ACTokenId("AC_PACKAGE_TARNAME", "autoconf", regExCounter++),
            new ACTokenId("AC_PACKAGE_URL", "autoconf", regExCounter++),
            new ACTokenId("AC_PACKAGE_VERSION", "autoconf", regExCounter++),
            new ACTokenId("AC_PATH_PROG", "autoconf", regExCounter++),
            new ACTokenId("AC_PATH_PROGS", "autoconf", regExCounter++),
            new ACTokenId("AC_PATH_PROGS_FEATURE_CHECK", "autoconf", regExCounter++),
            new ACTokenId("AC_PATH_TARGET_TOOL", "autoconf", regExCounter++),
            new ACTokenId("AC_PATH_TOOL", "autoconf", regExCounter++),
            new ACTokenId("AC_PATH_X", "autoconf", regExCounter++),
            new ACTokenId("AC_PATH_XTRA", "autoconf", regExCounter++),
            new ACTokenId("AC_PREFIX_DEFAULT", "autoconf", regExCounter++),
            new ACTokenId("AC_PREFIX_PROGRAM", "autoconf", regExCounter++),
            new ACTokenId("AC_PREPROC_IFELSE", "autoconf", regExCounter++),
            new ACTokenId("AC_PREREQ", "autoconf", regExCounter++),
            new ACTokenId("AC_PRESERVE_HELP_ORDER", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_AWK", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_CC", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_CC_C_O", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_CC_C89", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_CC_C99", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_CC_STDC", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_CPP", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_CPP_WERROR", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_CXX", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_CXX_C_O", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_CXXCPP", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_EGREP", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_F77", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_F77_C_O", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_FC", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_FC_C_O", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_FGREP", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_GCC_TRADITIONAL", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_GO", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_GREP", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_INSTALL", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_LEX", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_LN_S", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_MAKE_SET", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_MKDIR_P", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_OBJC", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_OBJCPP", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_OBJCXX", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_OBJCXXCPP", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_RANLIB", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_SED", "autoconf", regExCounter++),
            new ACTokenId("AC_PROG_YACC", "autoconf", regExCounter++),
            new ACTokenId("AC_REPLACE_FNMATCH", "autoconf", regExCounter++),
            new ACTokenId("AC_REPLACE_FUNCS", "autoconf", regExCounter++),
            new ACTokenId("AC_REQUIRE", "autoconf", regExCounter++),
            new ACTokenId("AC_REQUIRE_AUX_FILE", "autoconf", regExCounter++),
            new ACTokenId("AC_REQUIRE_CPP", "autoconf", regExCounter++),
            new ACTokenId("AC_REVISION", "autoconf", regExCounter++),
            new ACTokenId("AC_RUN_IFELSE", "autoconf", regExCounter++),
            new ACTokenId("AC_SEARCH_LIBS", "autoconf", regExCounter++),
            new ACTokenId("AC_STRUCT_DIRENT_D_INO", "autoconf", regExCounter++),
            new ACTokenId("AC_STRUCT_DIRENT_D_TYPE", "autoconf", regExCounter++),
            new ACTokenId("AC_STRUCT_ST_BLOCKS", "autoconf", regExCounter++),
            new ACTokenId("AC_STRUCT_TM", "autoconf", regExCounter++),
            new ACTokenId("AC_STRUCT_TIMEZONE", "autoconf", regExCounter++),
            new ACTokenId("AC_SUBST", "autoconf", regExCounter++),
            new ACTokenId("AC_SUBST_FILE", "autoconf", regExCounter++),
            new ACTokenId("AC_SYS_INTERPRETER", "autoconf", regExCounter++),
            new ACTokenId("AC_SYS_LARGEFILE", "autoconf", regExCounter++),
            new ACTokenId("AC_SYS_LONG_FILE_NAMES", "autoconf", regExCounter++),
            new ACTokenId("AC_SYS_POSIX_TERMIOS", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_GETGROUPS", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_INT8_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_INT16_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_INT32_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_INT64_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_INTMAX_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_INTPTR_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_LONG_DOUBLE", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_LONG_DOUBLE_WIDER", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_LONG_LONG_INT", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_MBSTATE_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_MODE_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_OFF_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_PID_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_SIZE_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_SSIZE_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_UID_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_UINT8_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_UINT16_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_UINT32_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_UINT64_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_UINTMAX_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_UINTPTR_T", "autoconf", regExCounter++),
            new ACTokenId("AC_TYPE_UNSIGNED_LONG_LONG_INT", "autoconf", regExCounter++),
            new ACTokenId("AC_USE_SYSTEM_EXTENSIONS", "autoconf", regExCounter++),
            new ACTokenId("AC_WARNING", "autoconf", regExCounter++),
            // Autoconf obsolete macros
            new ACTokenId("AC_AIX", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_ALLOCA", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_ARG_ARRAY", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_C_CROSS", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_C_LONG_DOUBLE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_CANONICAL_SYSTEM", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_CHAR_UNSIGNED", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_CHECKING", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_COMPILE_CHECK", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_CONST", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_CROSS_CHECK", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_CYGWIN", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_DECL_SYS_SIGLIST", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_DECL_YYTEXT", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_DIR_HEADER", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_DYNIX_SEQ", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_EXEEXT", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_EMXOS2", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_ENABLE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_ERROR", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_FIND_X", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_FIND_XTRA", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_FOREACH", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_FUNC_CHECK", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_FUNC_SETVBUF_REVERSED", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_FUNC_WAIT3", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_GCC_TRADITIONAL", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_GETGROUPS_T", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_GETLOADAVG", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_GNU_SOURCE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_HAVE_FUNCS", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_HAVE_HEADERS", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_HAVE_LIBRARY", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_HAVE_POUNDBANG", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_HEADER_CHECK", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_HEADER_EGREP", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_HELP_STRING", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_INLINE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_INT_16_BITS", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_IRIX_SUN", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_ISC_POSIX", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_LANG_C", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_LANG_CPLUSPLUS", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_LANG_FORTRAN77", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_LANG_RESTORE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_LANG_SAVE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_LINK_FILES", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_LN_S", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_LONG_64_BITS", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_LONG_DOUBLE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_LONG_FILE_NAMES", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_MAJOR_HEADER", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_MEMORY_H", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_MINGW32", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_MINIX", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_MINUS_C_MINUS_O", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_MMAP", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_MODE_T", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_OBJEXT", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_OBSOLETE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_OFF_T", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_OUTPUT_COMMANDS", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_PID_T", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_PREFIX", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_PROGRAMS_CHECK", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_PROGRAMS_PATH", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_PROGRAM_CHECK", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_PROGRAM_EGREP", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_PROGRAM_PATH", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_REMOTE_TAPE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_RESTARTABLE_SYSCALLS", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_RETSIGTYPE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_RSH", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_SCO_INTL", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_SETVBUF_REVERSED", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_SET_MAKE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_SIZEOF_TYPE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_SIZE_T", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_STAT_MACROS_BROKEN", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_STDC_HEADERS", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_STRCOLL", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_STRUCT_ST_BLKSIZE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_STRUCT_ST_RDEV", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_ST_BLKSIZE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_ST_BLOCKS", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_ST_RDEV", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_SYS_RESTARTABLE_SYSCALLS", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_SYS_SIGLIST_DECLARED", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_TEST_CPP", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_TEST_PROGRAM", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_TIMEZONE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_TIME_WITH_SYS_TIME", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_TRY_COMPILE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_TRY_CPP", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_TRY_LINK", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_TRY_LINK_FUNC", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_TRY_RUN", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_TYPE_SIGNAL", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_UID_T", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_UNISTD_H", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_USG", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_UTIME_NULL", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_VALIDATE_CACHED_SYSTEM_TUPLE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_VERBOSE", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_VFORK", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_VPRINTF", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_WAIT3", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_WARN", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_WITH", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_WORDS_BIGENDIAN", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_XENIX_DIR", "autoconf-obsolete", regExCounter++),
            new ACTokenId("AC_YYTEXT_POINTER", "autoconf-obsolete", regExCounter++),
            // Autoconf AH macros
            new ACTokenId("AH_BOTTOM", "autoconf-ah-keyword", regExCounter++),
            new ACTokenId("AH_HEADER", "autoconf-ah-keyword", regExCounter++),
            new ACTokenId("AH_TEMPLATE", "autoconf-ah-keyword", regExCounter++),
            new ACTokenId("AH_TOP", "autoconf-ah-keyword", regExCounter++),
            new ACTokenId("AH_VERBATIM", "autoconf-ah-keyword", regExCounter++),
            // Autoconf AM macros
            new ACTokenId("AM_INIT_AUTOMAKE", "autoconf-am-keyword", regExCounter++),
            new ACTokenId("AM_CONDITIONAL", "autoconf-am-keyword", regExCounter++),
            // m4sh macros
            new ACTokenId("AS_BOURNE_COMPATIBLE", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_BOX", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_CASE", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_DIRNAME", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_ECHO", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_ECHO_N", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_ESCAPE", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_EXECUTABLE_P", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_EXIT", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_HELP_STRING", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_IF", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_INIT", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_INIT_GENERATED", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_LINENO_PREPARE", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_LITERAL_IF", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_LITERAL_WORD_IF", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_ME_PREPARE", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_MESSAGE_FD", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_MESSAGE_LOG_FD", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_MKDIR_P", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_ORIGINAL_STDIN_FD", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_SET_CATFILE", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_SET_STATUS", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_SHELL_SANITIZE", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_TMPDIR", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_TR_CPP", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_TR_SH", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_UNSET", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_VAR_APPEND", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_VAR_ARITH", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_VAR_COPY", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_VAR_IF", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_VAR_POPDEF", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_VAR_PUSHDEF", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_VAR_SET", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_VAR_SET_IF", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_VAR_TEST_SET", "autoconf-as-keyword", regExCounter++),
            new ACTokenId("AS_VERSION_COMPARE", "autoconf-as-keyword", regExCounter++),
            // Autoconf AU macros
            new ACTokenId("AU_ALIAS", "autoconf-au-keyword", regExCounter++),
            new ACTokenId("AU_DEFUN", "autoconf-au-keyword", regExCounter++),
            // Autoconf AC_* macro
            new ACTokenId("AC_MACRO_PRIVATE", "autoconf-ac-generic-keyword", regExCounter++),
            new ACTokenId("AC_MACRO", "autoconf-ac-generic-keyword", regExCounter++),
            new ACTokenId("AC_VARIABLE", "autoconf-ac-generic-keyword", regExCounter++),
            // Autoconf AH_* macro
            new ACTokenId("AH_MACRO_PRIVATE", "autoconf-ah-generic-keyword", regExCounter++),
            new ACTokenId("AH_MACRO", "autoconf-ah-generic-keyword", regExCounter++),
            new ACTokenId("AH_VARIABLE", "autoconf-ah-generic-keyword", regExCounter++),
            // Autoconf AM_* macro
            new ACTokenId("AM_MACRO_PRIVATE", "autoconf-am-generic-keyword", regExCounter++),
            new ACTokenId("AM_MACRO", "autoconf-am-generic-keyword", regExCounter++),
            new ACTokenId("AM_VARIABLE", "autoconf-am-generic-keyword", regExCounter++),
            // Autoconf AN_* macro
            new ACTokenId("AN_MACRO_PRIVATE", "autoconf-an-generic-keyword", regExCounter++),
            new ACTokenId("AN_MACRO", "autoconf-an-generic-keyword", regExCounter++),
            new ACTokenId("AN_VARIABLE", "autoconf-an-generic-keyword", regExCounter++),
            // Autoconf AS_* macro
            new ACTokenId("AS_MACRO_PRIVATE", "autoconf-as-generic-keyword", regExCounter++),
            new ACTokenId("AS_MACRO", "autoconf-as-generic-keyword", regExCounter++),
            new ACTokenId("AS_VARIABLE", "autoconf-as-generic-keyword", regExCounter++),
            // Autoconf AX_* macro
            new ACTokenId("AX_MACRO_PRIVATE", "autoconf-ax-generic-keyword", regExCounter++),
            new ACTokenId("AX_MACRO", "autoconf-ax-generic-keyword", regExCounter++),
            new ACTokenId("AX_VARIABLE", "autoconf-ax-generic-keyword", regExCounter++),
            // Unknown macro type
            new ACTokenId("UNKNOWN_MACRO_PRIVATE", "unknown-keyword", regExCounter++),
            new ACTokenId("UNKNOWN_MACRO", "unknown-keyword", regExCounter++),
            new ACTokenId("UNKNOWN_VARIABLE", "unknown-keyword", regExCounter++),
            // m4 macro type
            new ACTokenId("MF_MACRO_PRIVATE", "m4-keyword", regExCounter++),
            new ACTokenId("MF_MACRO", "m4-keyword", regExCounter++),
            // Identifiers
            new ACTokenId("IDENTIFIER", "identifier", regExCounter++),
            new ACTokenId("LETTER", "identifier", regExCounter++),
            new ACTokenId("PART_LETTER", "identifier", regExCounter++),
            // Text
            new ACTokenId("TEXT", "text", regExCounter++)
        });

        idToToken = new HashMap<Integer, ACTokenId>();

        for (ACTokenId token : tokens) {
            idToToken.put(token.ordinal(), token);
        }
    }

    static synchronized ACTokenId getToken(int id) {
        if (idToToken == null) {
            init();
        }

        return idToToken.get(id);
    }

    @Override
    protected Collection<ACTokenId> createTokenIds() {
        if (tokens == null) {
            init();
        }

        return tokens;
    }

    @Override
    protected Lexer<ACTokenId> createLexer(LexerRestartInfo<ACTokenId> info) {
        return new ACLexer(info);
    }

    @Override
    protected String mimeType() {
        return "text/x-autoconf";
    }
}
